/** Guidance follows review_task and accept_task_assignment server policies. */
export function workspaceHelpSteps(isAdmin:boolean){return [
 {title:'Find your way around',body:'Dashboard shows progress, deadlines and work needing your attention. Projects groups your team’s work. The selected navigation icon shows its name. On a phone, swipe the navigation row or use its arrows to discover more sections. Hold an icon to see its label; tap to open it. Help is always available at the top.',href:'/dashboard/insights',link:'Open Dashboard'},
 {title:'Assign a task',body:'Open a project and choose New Task. Add a clear title, deadline and priority, then select one or more project members. My Tasks shows work assigned to you; All Tasks shows work you can access. Private projects are limited to their permitted team.',href:'/dashboard',link:'Open Projects'},
 {title:'Accept your assignment',body:'Open a new task assigned to you and choose Accept task, or follow the acceptance button in its assignment email and sign in. Each assignee accepts separately. The creator receives a notification and an email when delivery is enabled. Acceptance confirms receipt; it does not change the task status or complete the work. Your accepted details move to the bottom.',href:'/dashboard/my-tasks',link:'Open My Tasks'},
 {title:'Work together and share updates',body:'Set the task to In progress when you start. Shared assignments have one status for everyone. The creator, any assignee or an admin can update that status. Use Updates for remarks and @mentions; press Enter to choose a suggested person, or Cmd/Ctrl + Enter to post your remark. Supporting files belong in Details → Add attachments.',href:'/dashboard/my-tasks',link:'Open My Tasks'},
 {title:'Submit work for review',body:'When the work is ready, the creator, any assignee or an admin can choose Ready for review. A task needs at least one assignee, and all assignees must be active. The status strip shows who can act next. While waiting, the creator, any assignee or an admin can use More status actions → Withdraw submission, with a reason, to return it to In progress.',href:'/dashboard/tasks',link:'Open All Tasks'},
 {title:'Review and complete',body:(isAdmin?'As an admin, you can approve any submitted task you can work on, including your own.':'As a member, you can approve a submitted task you created only if you are not one of its assignees and creator review is enabled. Otherwise, an admin reviews it.')+' Eligible reviewers choose Approve & complete or Request changes. Requested changes need a reason and return the shared task to In progress. Only the creator or an admin can reopen completed work, with a reason. Archived work is read-only.',href:'/dashboard/tasks?summary=in_review',link:'Open tasks awaiting review'},
 {title:'Follow notifications and deadlines',body:'Notifications brings together assignments, mentions, acceptance and review updates. Open an alert to see the related task or remark. Workspace-managed email includes assignment and review updates, a daily briefing from 11 AM IST for tasks due today, tomorrow or overdue (including work you delegated), and a personal weekly report on Mondays from 11 AM IST. In-app alert preferences are separate. Contact your workspace admin for access or delivery problems.',href:'/dashboard/notifications',link:'Open Notifications'}
];}
