'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import AssigneePicker from '@/components/AssigneePicker';
import {shiftDate} from '@/lib/planning-types';
import type {PlanningPreview,PlanTask} from '@/lib/planning-types';
import type {planningOptions} from '@/lib/planning';
import {todayKey} from '@/lib/task-presentation';
import {submitPlan,savePlanningTemplate} from './actions';
type Options=Awaited<ReturnType<typeof planningOptions>>;
const field='mt-1 w-full rounded-lg border p-2.5 text-sm';
export default function PlanningForm({preview,options,saveFirst}:{preview:PlanningPreview;options:Options;saveFirst:boolean}){
 const router=useRouter(),requestId=useRef('');const b=preview.blueprint,isProject=b.kind==='project';
 const [name,setName]=useState(b.name+' (copy)'),[description,setDescription]=useState(b.description);
 const [start,setStart]=useState(todayKey()),[members,setMembers]=useState<string[]>([options.user]),[memberQuery,setMemberQuery]=useState('');
 const [target,setTarget]=useState(options.projects.find(p=>p.id===preview.sourceProjectId&&p.writable)?.id||options.projects.find(p=>p.writable)?.id||'');
 const [tasks,setTasks]=useState<PlanTask[]>(b.tasks.map(t=>({...t,dueDate:t.offset===null?'':shiftDate(todayKey(),t.offset),assigneeIds:[]})));
 const [templateName,setTemplateName]=useState(b.name),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 const choices=options.people.filter(p=>isProject?members.includes(p.id):options.memberships.some(m=>m.project_id===target&&m.user_id===p.id));
 function edit(index:number,patch:Partial<PlanTask>){setTasks(old=>old.map((t,i)=>i===index?{...t,...patch}:t));setDirty(true);}
 async function save(){setBusy(true);setError('');try{const result=await savePlanningTemplate(preview.source,preview.version,templateName);if(result.error)setError(result.error);else setSaved(true);}catch{setError('Connection interrupted. Check your templates before saving again.');}finally{setBusy(false);}}
 return <div className="mx-auto max-w-4xl space-y-6"><div><Link href="/dashboard/templates" className="text-sm text-blue-600 underline" onClick={e=>{if(dirty&&!confirm('Discard your unsaved copy?'))e.preventDefault();}}>Templates</Link><h1 className="mt-2 text-2xl font-bold">{preview.source.kind==='template'?'Use template':`Duplicate ${b.kind}`}</h1><p className="mt-2 text-sm text-gray-500">Review {tasks.length} {tasks.length===1?'task':'tasks'}, assignees and deadlines before creating new work.</p></div>
 <div className="rounded-xl border bg-surface p-4 text-sm"><p>Copies start in To do with unchecked checklists. You become the creator. New projects are private.</p><p className="mt-2 text-gray-500">Only active tasks are included in project copies. Remarks, notes, attachments, approvals, history and recurring schedules are excluded. Dependencies between copied tasks are kept; links to other tasks are excluded.</p></div>
 <details open={saveFirst||undefined} className="rounded-xl border bg-surface p-4"><summary className="cursor-pointer font-medium">Save this source as a reusable template</summary><p className="mt-3 text-sm text-gray-500">Saves the source titles, descriptions, priorities, checklist steps and relative deadlines. Your draft changes below are for this copy only. Templates are personal and require continued access to the original project.</p><div className="mt-3 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm">Template name<input aria-label="Template name" value={templateName} onChange={e=>{setTemplateName(e.target.value);setSaved(false);}} maxLength={200} className={field}/></label><button type="button" disabled={busy||saved||!templateName.trim()} onClick={save} className="rounded-lg border px-4 py-2.5 text-sm">{saved?'Template saved':'Save template'}</button></div>{saved&&<p role="status" className="mt-2 text-sm">Saved to your templates.</p>}</details>
 {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error} <button type="button" className="underline" onClick={()=>{if(!dirty||confirm('Reloading replaces your draft. Continue?'))window.location.reload();}}>Reload preview</button></p>}
 <form onChange={()=>setDirty(true)} onSubmit={async e=>{e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);const finalTasks=tasks.map((t,i)=>({...t,assigneeIds:JSON.parse(String(form.get('assignees-'+i)||'[]')) as string[]}));setBusy(true);setError('');if(!requestId.current)requestId.current=crypto.randomUUID();try{const result=await submitPlan({source:preview.source,version:preview.version,requestId:requestId.current,name,description,targetProjectId:target,members,tasks:finalTasks});if(result.error)setError(result.error);else if('projectId' in result){setDirty(false);router.push('/dashboard/projects/'+result.projectId+(result.taskId?'?task='+result.taskId:''));router.refresh();}}catch{setError('Connection interrupted. Retry with the same choices to recover your copy without creating a duplicate.');}finally{setBusy(false);}}} className="space-y-6">
 <fieldset disabled={busy} className="space-y-6"><div className="grid gap-4 rounded-xl border bg-surface p-5"><label className="text-sm font-medium">{isProject?'New project name':'New task title'}<input aria-label={isProject?'New project name':'New task title'} required maxLength={200} value={name} onChange={e=>setName(e.target.value)} className={field}/></label><label className="text-sm font-medium">Description<textarea aria-label="Copy description" maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} rows={3} className={field}/></label>
 {!isProject&&<label className="text-sm font-medium">Destination project<select aria-label="Destination project" required value={target} onChange={e=>setTarget(e.target.value)} className={field}><option value="">Choose a project</option>{options.projects.filter(p=>p.writable).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><span className="mt-1 block text-xs text-gray-500">Changing the destination clears the assignee selections.</span></label>}
 {isProject&&<fieldset><legend className="text-sm font-medium">New project members</legend><input aria-label="Search new project members" value={memberQuery} onChange={e=>setMemberQuery(e.target.value)} placeholder="Search by name or email" className={field}/><div className="mt-2 max-h-40 overflow-y-auto rounded-lg border p-2">{options.people.filter(p=>(p.full_name+' '+p.email).toLowerCase().includes(memberQuery.toLowerCase())).map(p=><label key={p.id} className="flex items-center gap-2 p-2 text-sm"><input type="checkbox" checked={members.includes(p.id)} disabled={p.id===options.user} onChange={e=>setMembers(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/>{p.full_name||p.email}{p.id===options.user?' (you)':''}</label>)}</div><p className="mt-1 text-xs text-gray-500">Choose members before assigning tasks. Changing membership clears assignee selections.</p></fieldset>}
 <div className="flex flex-wrap items-end gap-3"><label className="text-sm font-medium">First deadline<input aria-label="First deadline" type="date" min="2000-01-01" max="2100-12-31" value={start} onChange={e=>setStart(e.target.value)} className={field}/></label><button type="button" className="rounded-lg border px-3 py-2.5 text-sm" onClick={()=>{setTasks(old=>old.map(t=>({...t,dueDate:b.tasks.find(s=>s.key===t.key)?.offset==null?'':shiftDate(start,b.tasks.find(s=>s.key===t.key)!.offset!)})));setDirty(true);}}>Shift all deadlines</button><button type="button" className="rounded-lg border px-3 py-2.5 text-sm" onClick={()=>{setTasks(old=>old.map(t=>({...t,dueDate:''})));setDirty(true);}}>Clear deadlines</button></div><p className="text-xs text-gray-500">Original date spacing is preserved. Undated tasks stay undated until you set their deadline below. Dates use Asia/Kolkata.</p></div>
 <section aria-label="Copy task preview" className="space-y-3"><h2 className="text-lg font-semibold">Task preview</h2>{!tasks.length&&<p className="text-sm text-gray-500">This creates an empty project. You can add tasks afterwards.</p>}{tasks.map((task,i)=><details key={task.key} open={tasks.length===1||undefined} className="rounded-xl border bg-surface p-4"><summary className="cursor-pointer break-words font-medium">{task.title} <span className="ml-2 text-xs font-normal text-gray-500">{task.dueDate||'No deadline'} · {task.checklist.length} checklist steps</span></summary><div className="mt-4 grid gap-4">{isProject&&<><label className="text-sm">Task title<input aria-label={'Copy task title '+(i+1)} required maxLength={200} value={task.title} onChange={e=>edit(i,{title:e.target.value})} className={field}/></label><label className="text-sm">Task description<textarea maxLength={10000} value={task.description} onChange={e=>edit(i,{description:e.target.value})} className={field}/></label></>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Priority<select aria-label={'Copy priority '+(i+1)} value={task.priority} onChange={e=>edit(i,{priority:e.target.value})} className={field}>{['low','medium','high','urgent'].map(p=><option key={p}>{p}</option>)}</select></label><label className="text-sm">Deadline<input aria-label={'Copy deadline '+(i+1)} type="date" min="2000-01-01" max="2100-12-31" value={task.dueDate} onChange={e=>edit(i,{dueDate:e.target.value})} className={field}/></label></div><AssigneePicker key={target+members.join(',')} members={choices} name={'assignees-'+i}/>{task.checklist.length>0&&<div><h3 className="text-sm font-medium">Checklist (starts unchecked)</h3><ul className="mt-2 space-y-1 text-sm text-gray-500">{task.checklist.map((c,j)=><li key={j} className="break-words">□ {c}</li>)}</ul></div>}</div></details>)}</section>
 <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-surface p-4"><p className="text-sm text-gray-500">{tasks.length} new tasks · To do · No recurring schedules</p><button disabled={busy||(!isProject&&!target)} type="submit" className="rounded-lg bg-blue-600 px-5 py-2.5 font-medium text-white">{busy?'Saving…':isProject?'Create project copy':'Create task copy'}</button></div></fieldset></form></div>;
}
