import Link from 'next/link';
import {calendarData,planningOptions} from '@/lib/planning';
import {validDate,shiftDate} from '@/lib/planning-types';
import {todayKey} from '@/lib/task-presentation';
export default async function CalendarPage({searchParams}:{searchParams:Promise<{date?:string;view?:string;project?:string;assignee?:string}>}){
 const p=await searchParams,today=todayKey(),date=p.date&&validDate(p.date)?p.date:today,mode=p.view==='week'?'week':'month';
 const options=await planningOptions(),project=options.projects.some(x=>x.id===p.project)?p.project!:'',assignee=options.people.some(x=>x.id===p.assignee)?p.assignee!:'';
 const data=await calendarData(date,mode,project,assignee);
 const url=(d:string,v=mode)=>'/dashboard/calendar?'+new URLSearchParams({date:d,view:v,project,assignee}).toString();
 const monthMove=(n:number)=>{const d=new Date(date+'T00:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,10);};
 const days:string[]=[];for(let d=data.from;d&&d<=data.to;d=shiftDate(d,1))days.push(d);
 const display=(d:string,short=false)=>new Intl.DateTimeFormat('en-IN',{timeZone:'UTC',...(short?{weekday:'short',day:'numeric'}:{month:'long',year:'numeric'})}).format(new Date(d+'T00:00:00Z'));
 return <section className="space-y-5"><header><h1 className="text-2xl font-bold">Calendar</h1><p className="mt-2 text-sm text-gray-500">Plan deadlines across active projects. Each shared task appears once. Dates use Asia/Kolkata.</p></header>
 <form className="flex flex-wrap items-end gap-3 rounded-xl border bg-surface p-4"><input type="hidden" name="view" value={mode}/><label className="text-sm">Go to date<input aria-label="Go to date" type="date" name="date" defaultValue={date} min="2000-01-01" max="2100-12-31" className="mt-1 block rounded-lg border p-2.5"/></label><label className="min-w-0 text-sm">Project<select aria-label="Calendar project" name="project" defaultValue={project} className="mt-1 block w-full max-w-64 rounded-lg border p-2.5"><option value="">All projects</option>{options.projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="min-w-0 text-sm">Assignee<select aria-label="Calendar assignee" name="assignee" defaultValue={assignee} className="mt-1 block w-full max-w-64 rounded-lg border p-2.5"><option value="">Everyone</option>{options.people.map(x=><option key={x.id} value={x.id}>{x.full_name||x.email}</option>)}</select></label><button className="rounded-lg border px-4 py-2.5 text-sm">Apply filters</button></form>
 <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-2"><Link aria-label="Previous period" className="rounded-lg border px-3 py-2" href={url(mode==='week'?shiftDate(date,-7):monthMove(-1))}>←</Link><h2 className="text-lg font-semibold">{mode==='week'?display(data.from,true)+' – '+display(data.to,true):display(date)}</h2><Link aria-label="Next period" className="rounded-lg border px-3 py-2" href={url(mode==='week'?shiftDate(date,7):monthMove(1))}>→</Link><Link className="rounded-lg border px-3 py-2 text-sm" href={url(today)}>Today</Link></div><nav aria-label="Calendar view" className="flex rounded-lg border p-1">{['month','week'].map(v=><Link key={v} aria-current={v===mode?'page':undefined} className={`rounded-md px-3 py-2 text-sm ${v===mode?'bg-blue-600 text-white':''}`} href={url(date,v)}>{v==='month'?'Month':'Week'}</Link>)}</nav></div>
 <div className="flex flex-wrap justify-between gap-2 text-sm text-gray-500"><p>{data.total} tasks in this period</p><Link className="underline" href={'/dashboard/tasks?'+new URLSearchParams({project,assignee,summary:'undated'})}>{data.undated} tasks without deadlines</Link></div>
 {data.total>500&&<p role="status" className="rounded-lg border p-3 text-sm">Showing the first 500 tasks. Filter by project or assignee to see a smaller calendar.</p>}
 <div aria-label="Task calendar" className="grid gap-2 md:grid-cols-7">{days.map(day=>{const tasks=data.items.filter(t=>t.due_date===day);return <article key={day} aria-label={day} className={`min-w-0 rounded-lg border bg-surface p-2 ${day===today?'ring-2 ring-blue-500':''} ${!tasks.length?'hidden md:block':''}`}><h3 className={`mb-2 text-sm font-medium ${day.slice(0,7)!==date.slice(0,7)&&mode==='month'?'text-gray-500':''}`}><time dateTime={day}>{display(day,true)}</time>{day===today&&<span className="ml-1 text-xs text-blue-600">Today</span>}</h3><ul className="space-y-2">{tasks.map(t=><li key={t.id}><Link href={`/dashboard/projects/${t.project_id}?task=${t.id}`} className="block break-words rounded-md border p-2 text-sm transition hover:bg-blue-50"><strong className={t.status==='done'?'text-gray-500':'text-gray-900'}>{t.title}</strong><span className="mt-1 block text-xs text-gray-500">{t.project_name}</span><span className="mt-1 block text-xs text-gray-500">{t.assignees||'Unassigned'}</span><span className="mt-1 block text-xs text-blue-600">{t.status==='done'?'Completed':t.status==='in_review'?'Awaiting review':t.status.replaceAll('_',' ')}</span></Link></li>)}</ul></article>;})}</div>{!data.total&&<div className="rounded-xl border bg-surface p-8 text-center"><h2 className="font-semibold">No deadlines in this period</h2><p className="mt-2 text-sm text-gray-500">Choose another period or set a deadline on a task.</p></div>}<p className="text-xs text-gray-500 md:hidden">On phones, days with tasks are shown as an agenda. Tap a task to open its details.</p>
 </section>;
}
