/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript');
const exportsUnderTest={};new Function('exports',ts.transpileModule(fs.readFileSync('src/lib/history-presentation.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(exportsUnderTest);
const {historyAction,groupHistory}=exportsUnderTest;
const base={project_id:'p',task_id:'t',actor_id:'a',actor_name:'Alex',created_at:'2026-09-28T00:00:00Z',title:'Launch',project_name:'Campaign',project_exists:true,task_exists:true,transaction_id:'123'};
const review={...base,id:'review',entity:'Reviews',action:'created',changes:{decision:{after:'approve'},reason:{after:''}}};
const status={...base,id:'status',entity:'Tasks',action:'updated',changes:{status:{before:'in_review',after:'done'}}};
test('one explicit transaction links approval and status without losing raw records',()=>{const groups=groupHistory([status,review]);assert.equal(groups.length,1);assert.equal(groups[0][0].id,'review');assert.deepEqual(groups.flat().map(x=>x.id).sort(),['review','status']);});
test('same timestamps, different actors/tasks, missing links and ambiguous reviews never merge',()=>{for(const patch of [{transaction_id:null},{transaction_id:'124'},{actor_id:'b'},{task_id:'other'}])assert.equal(groupHistory([status,{...review,...patch}]).length,2);assert.equal(groupHistory([status,review,{...review,id:'second'}]).length,3);assert.equal(groupHistory([{...status,changes:{...status.changes,priority:{after:'high'}}},review]).length,2);});
test('readable review, membership and completion descriptions',()=>{const names=new Map([['maya','Maya']]);assert.equal(historyAction(review,names),'approved the task');assert.equal(historyAction({...review,changes:{decision:{after:'submit'}}},names),'submitted the task for review');assert.equal(historyAction({...base,entity:'Projects',action:'membership created',changes:{user_id:{after:'maya'}}},names),'added Maya to the project');assert.equal(historyAction({...base,entity:'Projects',action:'updated',changes:{is_archived:{after:true},completed_at:{after:'2026-09-28'}}},names),'completed the project');});
