import {chromium,expect} from '@playwright/test';
import pg from 'pg';
import {randomBytes,scrypt as callback} from 'node:crypto';
import {promisify} from 'node:util';
import assert from 'node:assert/strict';
// Synthetic CI database only. Never point this runner at an existing workspace.
const db=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});await db.connect();
if((await db.query('SELECT id FROM profiles LIMIT 1')).rows.length)throw new Error('Browser test requires an empty database.');
const password='Synthetic-browser-password-2026';
const salt=randomBytes(16).toString('hex'),key=await promisify(callback)(password,salt,64,{N:32768,r:8,p:3,maxmem:64*1024*1024});
const users=[];
for(let n=0;n<8;n++){
  const email=`staging${n}@collegedunia.com`;
  const id=(await db.query('INSERT INTO auth.users(id,email,password_hash) VALUES(gen_random_uuid(),$1,$2) RETURNING id',[email,`scrypt-v1$${salt}$${key.toString('hex')}`])).rows[0].id;
  await db.query('INSERT INTO profiles(id,email,full_name,role) VALUES($1,$2,$3,$4)',[id,email,`Staging ${n}`,n===0?'admin':'member']);users.push({id,email});
}
await db.query('UPDATE review_settings SET enabled=true');
const browser=await chromium.launch();const contexts=[];const pages=[];const external=[];
const base='http://localhost:3104';
try{
  for(let n=0;n<8;n++){
    const context=await browser.newContext();contexts.push(context);const page=await context.newPage();pages.push(page);
    page.on('request',request=>{if(request.url().includes('supabase.co'))external.push(request.url());});
  }
  const homeResponse=await pages[0].goto(base+'/');
  assert.equal(homeResponse.status(),200);
  await expect(pages[0].getByRole('heading',{level:1})).toContainText('Great work starts');
  await pages[0].getByRole('link',{name:'Open workspace'}).click();
  await pages[0].waitForURL('**/login');
  await Promise.all(pages.map(async(page,n)=>{await page.goto(base+'/login');await page.locator('input[name=email]').fill(users[n].email);await page.locator('input[name=password]').fill(password);await page.getByRole('button',{name:'Sign In',exact:true}).click();await page.waitForURL('**/dashboard',{timeout:30000});}));
  const admin=pages[0],member=pages[1],outsider=pages[2];
  await admin.getByRole('button',{name:'New Project'}).click();
  await admin.locator('dialog input[name=name]').fill('Private staging workflow');
  await admin.getByLabel('Search team members',{exact:true}).fill(users[1].email.toUpperCase());
  await admin.locator(`input[name=members][value="${users[1].id}"]`).check();
  await admin.getByLabel('Search team members',{exact:true}).fill('No matching person');
  await expect(admin.getByText('No members match your search.',{exact:true})).toBeVisible();
  await expect(admin.getByText('0 matching members · 1 selected',{exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Create Project',exact:true}).click();
  await admin.getByRole('link').filter({hasText:'Private staging workflow'}).click();
  await admin.waitForURL('**/dashboard/projects/*');
  const projectURL=admin.url();
  await expect(admin.getByText('Created by Staging 0',{exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Add Task',exact:true}).click();
  await admin.locator('dialog input[name=title]').fill('Retained task draft');
  await admin.getByRole('button',{name:'Add a teammate from the Team tab'}).click();
  await admin.getByLabel('Search teammates to add',{exact:true}).fill(users[2].email.toUpperCase());
  await expect(admin.locator('#newProjectMemberSelect option')).toHaveCount(2);
  await admin.getByLabel('Teammate to add',{exact:true}).selectOption(users[2].id);
  await admin.getByLabel('Search teammates to add',{exact:true}).fill('No matching person');
  await expect(admin.getByRole('button',{name:'Add to Project',exact:true})).toBeDisabled();
  await expect(admin.getByText('No teammates match your search.',{exact:true})).toBeVisible();
  await admin.getByLabel('Search teammates to add',{exact:true}).fill('');
  await expect(admin.getByRole('button',{name:'Resume task draft'})).toBeVisible();
  await admin.getByRole('button',{name:'Resume task draft'}).click();
  await expect(admin.locator('dialog input[name=title]')).toHaveValue('Retained task draft');
  await admin.locator('dialog input[name=title]').fill('Verify local task workflow');
  await admin.getByRole('checkbox',{name:'Staging 1',exact:true}).check();
  await admin.getByRole('button',{name:'Create task',exact:true}).click();
  await expect.poll(async()=>Number((await db.query('SELECT count(*) FROM tasks')).rows[0].count)).toBe(1);
  const task=(await db.query('SELECT id FROM tasks')).rows[0].id;
  await expect(admin.getByRole('button',{name:'Edit project',exact:true})).toBeHidden();
  await admin.getByText('Project actions',{exact:true}).click();
  await admin.keyboard.press('Escape');
  await expect(admin.getByRole('button',{name:'Edit project',exact:true})).toBeHidden();
  await admin.getByText('Project actions',{exact:true}).click();
  await admin.getByRole('button',{name:'Edit project',exact:true}).click();
  await expect(admin.locator('dialog')).toBeVisible();
  await admin.locator('dialog input[name=name]').fill('Unsaved project title');
  const discardPrompt=admin.waitForEvent('dialog');
  const escape=admin.keyboard.press('Escape');
  await (await discardPrompt).dismiss();await escape;
  await expect(admin.locator('dialog input[name=name]')).toHaveValue('Unsaved project title');
  await admin.locator('dialog input[name=name]').fill('Private staging workflow');
  await admin.keyboard.press('Escape');
  await expect(admin.locator('dialog')).toHaveCount(0);
  for (const width of [1440,430]) {
    await admin.setViewportSize({width,height:932});
    const geometry=()=>admin.evaluate(()=>[...document.querySelectorAll('.workspace-main,.workspace-main h1,.dark-workspace-sidebar,.workspace-header-inner,.board-column,.task-card')].map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return [el.className,Math.round(r.x),Math.round(r.y),Math.round(r.width),Math.round(r.height),s.fontSize,s.padding,s.borderRadius,s.display];}));
    await admin.evaluate(()=>document.fonts.ready);
    await admin.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));
    const beforeTheme=await geometry();
    await admin.getByRole('button',{name:/Switch to (light|dark) mode/}).click();
    await admin.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));
    assert.deepEqual(await geometry(),beforeTheme,'Theme changes must preserve layout and typography');
    await admin.getByRole('button',{name:/Switch to (light|dark) mode/}).click();

    await admin.getByText('Project actions',{exact:true}).click();
    await expect.poll(async()=>{const box=await admin.locator('[data-actions-menu]').boundingBox();return box.x>=0&&box.x+box.width<=width;}).toBe(true);
    await admin.keyboard.press('Escape');
    await admin.getByRole('button',{name:'Table & export',exact:true}).click();
    await expect(admin.getByRole('region',{name:'Table view',exact:true})).toBeVisible();
    if(width===430)for(const select of await admin.locator('.task-table-view select').all())assert.ok((await select.boundingBox()).width>=140,'Mobile filters must keep their selected values readable');
    await admin.getByLabel('Show Created by column').check();
    await expect(admin.getByRole('columnheader',{name:'Created by',exact:true})).toBeVisible();
    await expect(admin.getByRole('cell',{name:'Staging 0',exact:true})).toBeVisible();
    await expect(admin.getByRole('region',{name:'Board view',exact:true})).toHaveCount(0);
    await admin.getByRole('button',{name:'Board',exact:true}).click();
    await expect(admin.getByRole('region',{name:'Board view',exact:true})).toBeVisible();
    await expect(admin.getByRole('region',{name:'Table view',exact:true})).toHaveCount(0);
    assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  }
  await admin.getByRole('button',{name:'Add Task',exact:true}).click();
  await admin.locator('dialog input[name=title]').fill('Separate unsaved draft');
  await admin.getByRole('button',{name:'Add a teammate from the Team tab'}).click();
  await admin.getByRole('button',{name:/^Tasks \(/}).click();
  await admin.getByRole('button',{name:'Open task: Verify local task workflow',exact:true}).click();
  await admin.getByText('Task actions',{exact:true}).click();
  const draftDiscard=admin.waitForEvent('dialog');
  const editExisting=admin.getByRole('button',{name:'Edit task',exact:true}).click();
  await (await draftDiscard).accept();await editExisting;
  await expect(admin.locator('dialog input[name=title]')).toHaveValue('Verify local task workflow');
  await admin.keyboard.press('Escape');
  await admin.goto(projectURL+'?task='+task);
  await expect(admin.getByRole('button',{name:'Edit task',exact:true})).toBeHidden();
  await admin.getByText('Task actions',{exact:true}).click();
  await admin.getByRole('button',{name:'Edit task',exact:true}).click();
  await expect(admin.locator('dialog input[name=title]')).toHaveValue('Verify local task workflow');
  await admin.keyboard.press('Escape');
  await admin.goto(projectURL+'?task='+task);
  await admin.getByRole('button',{name:/^Updates \(/}).click();
  await expect(admin.getByRole('heading',{name:'Task history',exact:true})).toBeVisible();
  assert.equal(await admin.evaluate(()=>{
    const notes=document.querySelector('textarea[aria-label="Write a task update"]');
    const history=[...document.querySelectorAll('h3')].find(el=>el.textContent==='Task history');
    return !!(notes.compareDocumentPosition(history)&Node.DOCUMENT_POSITION_FOLLOWING);
  }),true);

  await member.goto(projectURL+'?task='+task);
  await expect(member.getByText('Created by Staging 0',{exact:true}).last()).toBeVisible();
  await member.getByLabel('Task attachment').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic task attachment')});
  await member.getByRole('button',{name:'Upload file',exact:true}).click();
  await expect(member.getByRole('button',{name:/^proof.txt/})).toBeVisible();
  const attachment=(await db.query('SELECT id FROM task_attachments')).rows[0].id;
  const download=await contexts[1].request.get(base+'/api/attachments/'+attachment);assert.equal(download.status(),200);assert.equal(await download.text(),'Synthetic task attachment');
  assert.equal((await contexts[2].request.get(base+'/api/attachments/'+attachment)).status(),404);
  await member.getByRole('button',{name:'Ready for review',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[task])).rows[0].status).toBe('in_review');
  await expect(member.getByRole('button',{name:'Approve & complete',exact:true})).toBeHidden();
  await admin.goto(projectURL+'?task='+task);
  await admin.getByRole('button',{name:'Approve & complete',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[task])).rows[0].status).toBe('done');

  // Exercise archive/restore as a user without changing production records.
  await admin.goto(projectURL);
  await admin.getByText('Project actions',{exact:true}).click();
  await admin.getByRole('button',{name:'Complete project',exact:true}).click();
  await admin.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT is_archived FROM projects WHERE id=$1',[projectURL.split('/').pop()])).rows[0].is_archived).toBe(true);
  await admin.goto(base+'/dashboard/archive?section=completed');
  await expect(admin.getByRole('link',{name:'Private staging workflow',exact:true})).toBeVisible();
  await member.goto(projectURL+'?task='+task);
  await expect(member.getByRole('button',{name:'Ready for review',exact:true})).toBeHidden();
  await expect(member.getByLabel('Task attachment')).toHaveCount(0);
  assert.equal((await contexts[1].request.get(base+'/api/attachments/'+attachment)).status(),200);
  await admin.getByRole('button',{name:'Restore project',exact:true}).click();
  await admin.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT is_archived FROM projects WHERE id=$1',[projectURL.split('/').pop()])).rows[0].is_archived).toBe(false);
  await admin.goto(projectURL+'?task='+task);
  await admin.getByText('Task actions',{exact:true}).click();
  await admin.getByRole('button',{name:'Archive task',exact:true}).click();
  await admin.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT is_archived FROM tasks WHERE id=$1',[task])).rows[0].is_archived).toBe(true);
  await admin.goto(base+'/dashboard/archive');
  await expect(admin.getByRole('link',{name:'Verify local task workflow',exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Restore task',exact:true}).click();
  await admin.getByRole('button',{name:'Confirm',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT is_archived FROM tasks WHERE id=$1',[task])).rows[0].is_archived).toBe(false);
  await admin.getByText('Automatic archiving settings',{exact:true}).click();
  await admin.getByLabel('tasks retention days').fill('45');
  await admin.getByRole('button',{name:'Save archiving settings',exact:true}).click();
  await expect(admin.getByRole('status')).toHaveText('Archiving settings saved.');
  await expect.poll(async()=>(await db.query('SELECT task_days FROM archive_settings')).rows[0].task_days).toBe(45);
  await member.goto(base+'/dashboard/archive');
  await expect(member.getByText('Automatic archiving settings',{exact:true})).toHaveCount(0);
  await admin.goto(base+'/admin/users');
  await admin.getByRole('textbox',{name:'Search members'}).fill(users[1].email);
  await admin.getByRole('button',{name:'Edit details',exact:true}).click();
  await admin.getByLabel('Job title',{exact:true}).fill('QA coordinator');
  await admin.getByLabel('Department',{exact:true}).fill('Workflow QA');
  await admin.getByRole('button',{name:'Save details',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT department FROM profiles WHERE id=$1',[users[1].id])).rows[0].department).toBe('Workflow QA');
  await admin.goto(projectURL);
  await admin.getByRole('button',{name:/^Notes \(/}).click();
  await admin.getByRole('button',{name:'New Note',exact:true}).click();
  await admin.locator('dialog input[name=title]').fill('Workflow audit note');
  await admin.locator('dialog textarea[name=content]').fill('Decisions and context stay with the project.');
  await admin.locator('dialog button[type=submit]').click();
  await expect(admin.getByText('Workflow audit note',{exact:true})).toBeVisible();
  await admin.goto(base+'/dashboard/workload');
  await expect(admin.getByRole('heading',{name:'Team workload'})).toBeVisible();
  await admin.getByRole('link',{name:'Staging 1: pending tasks',exact:true}).click();
  await expect(admin.getByLabel('Filter by assignee')).toHaveValue(users[1].id);
  await expect(admin.getByLabel('Task summary filter')).toHaveValue('pending');
  await admin.getByRole('button',{name:'Reset filters',exact:true}).click();
  await admin.getByLabel('Sort tasks').selectOption('title');
  await admin.reload();
  await expect(admin.getByLabel('Sort tasks')).toHaveValue('title');
  await admin.goto(base+'/dashboard/tasks');
  const downloadPromise=admin.waitForEvent('download');
  await admin.getByRole('button',{name:'Export CSV',exact:true}).click();
  assert.equal((await downloadPromise).suggestedFilename(),'tasktracker-tasks.csv');
  await member.goto(base+'/dashboard/notifications');
  await member.getByRole('button',{name:'Mark all as read',exact:true}).click();
  await expect.poll(async()=>Number((await db.query('SELECT count(*) FROM notifications WHERE user_id=$1 AND NOT is_read',[users[1].id])).rows[0].count)).toBe(0);
  await member.getByRole('button',{name:'Mark as unread',exact:true}).first().click();
  await member.getByLabel('Notification filter').selectOption('unread');
  await expect(member.locator('article')).toHaveCount(1);
  await member.getByRole('button',{name:'Mark as read',exact:true}).click();
  await expect(member.getByText('You’re all caught up.',{exact:true})).toBeVisible();
  // Release 3 member-created delegation and lifecycle flow, synthetic accounts only.
  const delegated=(await db.query("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Member delegation QA',$2,$3) RETURNING id",[projectURL.split('/').pop(),users[1].id,users[0].id])).rows[0].id;
  await admin.goto(projectURL+'?task='+delegated);
  await admin.getByRole('button',{name:'Ready for review',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[delegated])).rows[0].status).toBe('in_review');
  await expect(admin.getByRole('button',{name:'Approve & complete',exact:true})).toBeHidden();
  await member.goto(projectURL+'?task='+delegated);
  await expect(member.getByRole('button',{name:'Request changes',exact:true})).toBeDisabled();
  await member.getByLabel('Review feedback / reason').fill('Please revise the deliverable');
  await member.getByRole('button',{name:'Request changes',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[delegated])).rows[0].status).toBe('in_progress');
  await admin.reload();await admin.getByRole('button',{name:'Ready for review',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[delegated])).rows[0].status).toBe('in_review');
  await member.reload();await member.getByRole('button',{name:'Approve & complete',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[delegated])).rows[0].status).toBe('done');
  await admin.goto(base+'/admin/users');await admin.getByRole('textbox',{name:'Search members'}).fill(users[1].email);
  await admin.getByRole('button',{name:'Deactivate / reassign',exact:true}).click();
  await admin.getByLabel('Reason for access change').fill('Synthetic lifecycle test');
  await admin.getByRole('button',{name:'Confirm deactivation',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT disabled FROM auth.users WHERE id=$1',[users[1].id])).rows[0].disabled).toBe(true);
  await member.goto(base+'/dashboard');await member.waitForURL('**/login');
  await admin.getByLabel('Member account status').selectOption('inactive');
  await admin.getByRole('button',{name:'Reactivate / reassign',exact:true}).click();
  await admin.getByLabel('Reason for access change').fill('Restore synthetic access');
  await admin.getByRole('button',{name:'Confirm reactivation',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT disabled FROM auth.users WHERE id=$1',[users[1].id])).rows[0].disabled).toBe(false);
  console.log('Release 3 browser: member creator requests changes and approves delegated work; admin cannot self-approve; deactivation revokes existing browser session; reactivation preserves account.');
  console.log('UI audit: completion archive, project/task restore, read-only archived work, retained download, settings permissions, team details, project notes, workload and CSV export passed.');
  await outsider.goto(projectURL);await expect(outsider.getByText('Verify local task workflow',{exact:true})).toHaveCount(0);
  await Promise.all(pages.map(p=>p.goto(base+'/dashboard')));
  // Real PostgreSQL row locks: two eligible reviewers cannot approve one version twice.
  await db.query('INSERT INTO project_members(project_id,user_id) VALUES($1,$2)',[projectURL.split('/').pop(),users[3].id]);
  const raceTask=(await db.query("INSERT INTO tasks(project_id,title,created_by,assignee_id,status) VALUES($1,'Concurrent review QA',$2,$3,'in_review') RETURNING id",[projectURL.split('/').pop(),users[1].id,users[3].id])).rows[0].id;
  async function concurrentAs(id,sql,args){const c=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});await c.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('request.jwt.claim.sub',$1,true)",[id]);await c.query('SET LOCAL ROLE authenticated');const result=await c.query(sql,args);if(sql.startsWith('UPDATE')&&result.rowCount!==1)throw new Error('The actor no longer has permission to change this profile.');await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{await c.end();}}
  const approvals=await Promise.allSettled([users[0],users[1]].map(u=>concurrentAs(u.id,"SELECT review_task($1,0,'approve','')",[raceTask])));
  assert.equal(approvals.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(approvals.filter(r=>r.status==='rejected').length,1);
  await db.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[4].id]);
  const demotions=await Promise.allSettled([[users[0],users[4]],[users[4],users[0]]].map(([actor,target])=>concurrentAs(actor.id,"UPDATE profiles SET role='member' WHERE id=$1",[target.id])));
  assert.equal(demotions.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(demotions.filter(r=>r.status==='rejected').length,1);
  assert.equal(Number((await db.query("SELECT count(*) FROM profiles WHERE role='admin' AND is_active")).rows[0].count),1);
  await db.query("UPDATE profiles SET role='admin' WHERE id=$1",[users[0].id]);
  console.log('Real PostgreSQL concurrency: one winning approval per task version; competing admin demotions preserve an active administrator.');

  await member.goto(base+'/login');await member.locator('input[name=email]').fill(users[1].email);await member.locator('input[name=password]').fill(password);await member.getByRole('button',{name:'Sign In',exact:true}).click();await member.waitForURL('**/dashboard');
  // Release 4: synthetic collaboration, discovery, reporting and scale.
  const r4project=projectURL.split('/').pop();
  const r4task=(await db.query("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date,recurrence) VALUES($1,'Discovery specimen',$2,$3,current_date+1,'weekly') RETURNING id",[r4project,users[0].id,users[3].id])).rows[0].id;
  await admin.goto(projectURL+'?task='+r4task+'&discussion=true');
  await admin.getByLabel('Write a task update').fill('Please check @Staging 3');
  await admin.getByRole('button',{name:'Mention Staging 3',exact:true}).click();
  await admin.getByRole('button',{name:'Post update',exact:true}).click();
  await expect(admin.getByRole('button',{name:'Edit remark',exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Edit remark',exact:true}).click();
  await admin.getByLabel('Write a task update').fill('Discovery remark revised');
  await admin.getByRole('button',{name:'Save remark',exact:true}).click();
  await expect(admin.getByText('Discovery remark revised',{exact:true})).toBeVisible();
  await admin.getByRole('button',{name:'Edit history',exact:true}).click();
  await expect(admin.getByRole('heading',{name:'Previous remark versions'})).toBeVisible();
  assert.equal(Number((await db.query("SELECT count(*) FROM notifications WHERE user_id=$1 AND task_id=$2 AND dedupe_key LIKE 'mention:%'",[users[3].id,r4task])).rows[0].count),1);
  await admin.goto(projectURL+'?task='+r4task);
  await admin.getByText('Edit future occurrences',{exact:true}).click();
  await admin.getByLabel('Future task title',{exact:true}).fill('Next specimen');
  await admin.getByLabel('Pause schedule',{exact:true}).check();
  await admin.getByRole('button',{name:'Preview future schedule',exact:true}).click();
  await admin.getByRole('button',{name:'Confirm future schedule',exact:true}).click();
  await expect.poll(async()=>(await db.query('SELECT paused FROM task_schedules WHERE task_id=$1',[r4task])).rows[0].paused).toBe(true);
  assert.equal((await db.query('SELECT title FROM tasks WHERE id=$1',[r4task])).rows[0].title,'Discovery specimen');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=','base64');
  await admin.getByLabel('Task attachment').setInputFiles({name:'preview.png',mimeType:'image/png',buffer:png});
  await admin.getByRole('button',{name:'Upload file',exact:true}).click();
  await expect.poll(async()=>Number((await db.query('SELECT count(*) FROM task_attachments WHERE task_id=$1',[r4task])).rows[0].count)).toBe(1);
  const previewId=(await db.query('SELECT id FROM task_attachments WHERE task_id=$1',[r4task])).rows[0].id;
  const previewResponse=await contexts[0].request.get(base+'/api/attachments/'+previewId+'?preview=1');assert.equal(previewResponse.status(),200);assert.equal(previewResponse.headers()['content-type'],'image/png');assert.equal((await contexts[2].request.get(base+'/api/attachments/'+previewId+'?preview=1')).status(),404);
  await admin.goto(base+'/dashboard/search?q=Discovery');await expect(admin.getByText('Discovery specimen',{exact:true}).first()).toBeVisible();await expect(admin.getByText('Discovery remark revised',{exact:true})).toBeVisible();
  await outsider.goto(base+'/dashboard/search?q=Discovery');await expect(outsider.getByText('No accessible results match these words.',{exact:true})).toBeVisible();
  await admin.goto(base+'/dashboard/reports');await expect(admin.getByRole('heading',{name:'Completion events by week'})).toBeVisible();const reportExport=await contexts[0].request.get(base+'/api/reports/export?from=2020-01-01&to=2029-12-31');assert.equal(reportExport.status(),200,await reportExport.text());
  // Project preferences and shared-task review controls.
  await admin.goto(base+'/dashboard');await admin.getByRole('button',{name:'List view',exact:true}).click();await expect(admin.locator('[data-project-view="list"]')).toBeVisible();await admin.reload();await expect(admin.getByRole('button',{name:'List view',exact:true})).toHaveAttribute('aria-pressed','true');
  await admin.getByRole('button',{name:'Grid view',exact:true}).click();await admin.getByLabel('Grid size',{exact:true}).selectOption('small');await expect(admin.locator('[data-grid-size="small"]')).toBeVisible();await admin.getByLabel('Sort projects',{exact:true}).selectOption('name');await admin.reload();await expect(admin.getByLabel('Grid size',{exact:true})).toHaveValue('small');await expect(admin.getByLabel('Sort projects',{exact:true})).toHaveValue('name');
  await admin.goto(projectURL);await admin.getByRole('button',{name:'Add Task',exact:true}).click();await admin.locator('dialog input[name=title]').fill('Shared browser assignment');await admin.getByRole('checkbox',{name:'Staging 1',exact:true}).check();await admin.getByRole('checkbox',{name:'Staging 3',exact:true}).check();await admin.getByRole('button',{name:'Create task',exact:true}).click();
  const shared=await expect.poll(async()=>(await db.query("SELECT id FROM tasks WHERE title='Shared browser assignment'")).rows[0]?.id).toBeTruthy();void shared;
  const sharedId=(await db.query("SELECT id FROM tasks WHERE title='Shared browser assignment'")).rows[0].id;
  for(const n of [1,3]){await pages[n].goto(base+'/dashboard/my-tasks');await expect(pages[n].getByRole('link',{name:'Shared browser assignment',exact:true})).toBeVisible();}
  await pages[3].goto(projectURL+'?task='+sharedId);await expect(pages[3].getByRole('button',{name:'Approve & complete',exact:true})).toBeHidden();await pages[3].getByRole('button',{name:'Ready for review',exact:true}).click();await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[sharedId])).rows[0].status).toBe('in_review');await expect(pages[3].getByRole('button',{name:'Ready for review',exact:true})).toBeHidden();await expect(pages[3].getByRole('button',{name:'Approve & complete',exact:true})).toBeHidden();
  await admin.goto(projectURL+'?task='+sharedId);await expect(admin.getByRole('button',{name:'Approve & complete',exact:true})).toBeVisible();await admin.getByRole('button',{name:'Approve & complete',exact:true}).click();await expect.poll(async()=>(await db.query('SELECT status FROM tasks WHERE id=$1',[sharedId])).rows[0].status).toBe('done');await expect(admin.getByRole('button',{name:'Approve & complete',exact:true})).toBeHidden();
  console.log('Project list/grid sizes/sorting preferences and multi-assignee picker, My Tasks and permitted-only review buttons passed.');


  // Release 5: actual previews, private templates, copies and responsive calendar.
  await admin.setViewportSize({width:1280,height:900});
  await admin.goto(projectURL+'?task='+sharedId);await admin.getByText('Task actions',{exact:true}).click();await admin.getByRole('link',{name:'Duplicate task',exact:true}).click();
  await expect(admin.getByRole('heading',{name:'Duplicate task',exact:true})).toBeVisible();
  await admin.getByText('Save this source as a reusable template',{exact:true}).click();
  await admin.getByLabel('Template name',{exact:true}).fill('R5 personal template');await admin.getByRole('button',{name:'Save template',exact:true}).click();await expect(admin.getByText('Saved to your templates.',{exact:true})).toBeVisible();
  const templateId=(await db.query("SELECT id FROM planning_templates WHERE name='R5 personal template'")).rows[0].id;
  await admin.getByLabel('New task title',{exact:true}).fill('R5 shared copy');await admin.getByLabel('Copy deadline 1',{exact:true}).fill('2026-09-20');
  await admin.getByRole('checkbox',{name:'Staging 1',exact:true}).check();await admin.getByRole('checkbox',{name:'Staging 3',exact:true}).check();await admin.getByRole('button',{name:'Create task copy',exact:true}).click();await admin.waitForURL('**/dashboard/projects/*');
  await expect.poll(async()=>(await db.query("SELECT count(*) n FROM tasks WHERE title='R5 shared copy'")).rows[0].n).toBe('1');
  const r5copy=(await db.query("SELECT * FROM tasks WHERE title='R5 shared copy'")).rows[0];assert.equal(r5copy.status,'todo');assert.deepEqual(r5copy.assignee_ids,[users[1].id,users[3].id]);assert.equal(r5copy.created_by,users[0].id);
  await admin.goto(base+'/dashboard/templates');await admin.getByLabel('Search templates',{exact:true}).fill('R5 personal');await expect(admin.getByRole('heading',{name:'R5 personal template',exact:true})).toBeVisible();await admin.getByRole('link',{name:'Use template',exact:true}).click();await expect(admin.getByRole('heading',{name:'Use template',exact:true})).toBeVisible();await expect(admin.getByRole('checkbox',{checked:true})).toHaveCount(0);
  await outsider.goto(base+'/dashboard/planning?kind=template&id='+templateId);await expect(outsider.getByText('Template unavailable or source project access was removed.',{exact:true})).toBeVisible();
  await admin.goto(base+'/dashboard/planning?kind=project&id='+r4project);await admin.getByLabel('New project name',{exact:true}).fill('R5 project copy');await admin.getByRole('button',{name:'Create project copy',exact:true}).click();await admin.waitForURL('**/dashboard/projects/*');await expect.poll(async()=>(await db.query("SELECT id FROM projects WHERE name='R5 project copy'")).rows[0]?.id).toBeTruthy();
  const r5project=(await db.query("SELECT id,is_private FROM projects WHERE name='R5 project copy'")).rows[0];assert.equal(r5project.is_private,true);assert.equal(Number((await db.query('SELECT count(*) n FROM project_members WHERE project_id=$1',[r5project.id])).rows[0].n),1);assert.equal(Number((await db.query("SELECT count(*) n FROM tasks WHERE project_id=$1 AND (status<>'todo' OR cardinality(assignee_ids)>0 OR recurrence<>'none')",[r5project.id])).rows[0].n),0);
  assert.equal(Number((await db.query('SELECT count(*) n FROM task_attachments a JOIN tasks t ON t.id=a.task_id WHERE t.project_id=$1',[r5project.id])).rows[0].n),0);
  await admin.goto(base+'/dashboard/calendar?date=2026-09-20&project='+r4project+'&assignee='+users[1].id);await expect(admin.getByRole('heading',{name:'Calendar',exact:true})).toBeVisible();await expect(admin.getByRole('link').filter({hasText:'R5 shared copy'})).toHaveCount(1);await admin.getByRole('link',{name:'Week',exact:true}).click();await expect(admin.getByRole('link',{name:'Week',exact:true})).toHaveAttribute('aria-current','page');
  for(const width of [375,430]){await admin.setViewportSize({width,height:932});await expect.poll(()=>admin.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await admin.screenshot({path:`/tmp/release5-calendar-${width}.png`,fullPage:true});}
  await admin.getByRole('button',{name:'Switch to dark mode',exact:true}).click();await admin.screenshot({path:'/tmp/release5-calendar-dark-430.png',fullPage:true});
  await admin.getByRole('link').filter({hasText:'R5 shared copy'}).click();await expect(admin.getByRole('dialog').getByRole('heading',{name:'R5 shared copy',exact:true})).toBeVisible();
  for(const width of [375,430]){await admin.setViewportSize({width,height:932});await admin.goto(base+'/dashboard/planning?kind=template&id='+templateId);await expect.poll(()=>admin.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await admin.screenshot({path:`/tmp/release5-planning-dark-${width}.png`,fullPage:true});}
  await admin.setViewportSize({width:1280,height:900});
  await admin.getByRole('button',{name:'Switch to light mode',exact:true}).click();await admin.screenshot({path:'/tmp/release5-planning-light-desktop.png',fullPage:true});
  console.log('Release 5 browser: menu copies, personal template save/use/outsider denial, shared assignments, reset approval/status, private project defaults, attachment exclusion, calendar filters/single shared task, task navigation and 375/430px layouts passed.');

  await db.query("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date) SELECT $1,'Scale specimen '||lpad(n::text,4,'0'),$2,$3,current_date+(n%30) FROM generate_series(1,1000)n",[r4project,users[0].id,users[3].id]);
  await admin.goto(base+'/dashboard/tasks?q=Scale&sort=title');await expect(admin.getByText('1000 matching tasks',{exact:false})).toBeVisible();await expect(admin.locator('tbody tr')).toHaveCount(25);
  const first=await admin.locator('tbody tr').first().innerText();await admin.getByRole('button',{name:'Next',exact:true}).click();await expect(admin.getByText('Page 2 of 40',{exact:true})).toBeVisible();assert.notEqual(await admin.locator('tbody tr').first().innerText(),first);
  const allDownload=admin.waitForEvent('download');await admin.getByRole('button',{name:'Export CSV',exact:true}).click();const exported=await allDownload;const stream=await exported.createReadStream();let csv='';for await(const chunk of stream)csv+=chunk;assert.equal((csv.match(/Scale specimen/g)||[]).length,1000);
  for(const width of [375,430]){await admin.setViewportSize({width,height:932});await expect.poll(()=>admin.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
  const timings=await Promise.all(pages.map(async p=>{const start=Date.now();await p.goto(base+'/dashboard/search?q=Scale');return Date.now()-start;}));console.log('Release 4 eight-session search timings (ms): '+JSON.stringify(timings));
  console.log('Release 4 browser: own remark editing/history, one mention alert, private search, schedule pause/future-only template, content-sniffed private preview, reports/export, 1,000 task pagination/full CSV and 375/430px overflow checks passed.');

  assert.equal(external.length,0,'Staging must not contact Supabase');
  console.log('Eight browser logins, private project, task assignment, local upload/download, outsider denial, review and admin approval passed against PostgreSQL 16.');
}finally{await browser.close();await db.end();}
