import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const { PGlite }=require(process.env.PGLITE_PATH || '@electric-sql/pglite');
process.on('uncaughtException', e => { console.error(e.message, e.where || '', e.query || ''); process.exit(1); });
const db=new PGlite();
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
for(const f of ['001_base.sql','002_review.sql','003_workspace.sql','004_automation.sql','005_runtime.sql'])await db.exec(read('postgres/'+f));
const admin='00000000-0000-0000-0000-000000000001',owner='00000000-0000-0000-0000-000000000002',member='00000000-0000-0000-0000-000000000003',outsider='00000000-0000-0000-0000-000000000004';
for(const [id,role] of [[admin,'admin'],[owner,'member'],[member,'member'],[outsider,'member']]){
 await db.query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[id,id+'@collegedunia.com']);
 await db.query('INSERT INTO profiles(id,email,full_name,role) VALUES($1,$2,$3,$4)',[id,id+'@collegedunia.com',role,role]);
}
async function as(id){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id || '']);if(id)await db.exec('SET ROLE authenticated');}
async function rows(sql,args=[]){return (await db.query(sql,args)).rows;}
await as(owner);
const p=(await rows("SELECT create_workspace_project('Private QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
assert.equal((await rows('SELECT * FROM project_members WHERE project_id=$1',[p])).length,2);
const t=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Owner task',$2,$3) RETURNING id",[p,owner,member]))[0].id;
await as(outsider);assert.equal((await rows('SELECT * FROM projects WHERE id=$1',[p])).length,0);
await assert.rejects(()=>rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Forbidden',$2)",[p,outsider]));
await as(member);
assert.equal((await rows("UPDATE profiles SET role='admin' WHERE id=$1 RETURNING id",[member])).length,0);
await assert.rejects(()=>rows("UPDATE tasks SET title='Hijack' WHERE id=$1",[t]));
await rows("UPDATE tasks SET status='in_progress' WHERE id=$1",[t]);
await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await rows("UPDATE tasks SET status='in_review' WHERE id=$1",[t]);
await as(owner);await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await as(member);
const own=(await rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Member own task',$2) RETURNING id",[p,member]))[0].id;
await rows("UPDATE tasks SET title='Edited own task' WHERE id=$1",[own]);
const checklist=(await rows("INSERT INTO task_checklist(task_id,title) VALUES($1,'Check result') RETURNING id",[t]))[0].id;
await as(admin);await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await rows('UPDATE task_checklist SET completed=true WHERE id=$1',[checklist]);await rows("UPDATE tasks SET status='done' WHERE id=$1",[t]);
await as(owner);
await assert.rejects(()=>rows("INSERT INTO task_checklist(task_id,title) VALUES($1,'Late item')",[t]));
await assert.rejects(()=>rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[t,own]));
await rows("UPDATE tasks SET status='todo' WHERE id=$1",[t]);
await rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[t,own]);
await as(member);await assert.rejects(()=>rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[own,t]));
await assert.rejects(()=>rows('SELECT run_workspace_automation()'));
await as(admin);await rows('DELETE FROM task_dependencies WHERE task_id=$1',[t]);
await as(owner);
const recurring=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date,recurrence) VALUES($1,'Repeat QA',$2,$3,(now() AT TIME ZONE 'Asia/Kolkata')::date-1,'daily') RETURNING id",[p,owner,member]))[0].id;
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');
assert.equal((await rows('SELECT * FROM tasks WHERE recurrence_source=$1',[recurring])).length,1);
const counts=await rows('SELECT dedupe_key,count(*) n FROM notifications WHERE dedupe_key IS NOT NULL GROUP BY dedupe_key HAVING count(*)>1');assert.equal(counts.length,0);
assert.equal((await rows("SELECT next_task_date('2026-02-28','monthly','2026-01-31')::text d"))[0].d,'2026-03-31');
await as(owner);assert.ok((await rows('SELECT * FROM task_history WHERE task_id=$1',[t])).length>=4);
await assert.rejects(()=>rows("INSERT INTO task_history(task_id,field) VALUES($1,'fake')",[t]));
await as(member);await rows('DELETE FROM tasks WHERE id=$1',[own]);
await as(owner);await rows('UPDATE projects SET is_private=false WHERE id=$1',[p]);
await as(outsider);assert.equal((await rows('SELECT * FROM projects WHERE id=$1',[p])).length,1);
await assert.rejects(()=>rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Read only',$2)",[p,outsider]));
await as(owner);await rows('DELETE FROM projects WHERE id=$1',[p]);
await as(null);assert.equal((await rows('SELECT * FROM tasks WHERE project_id=$1',[p])).length,0);
console.log('Standalone schema: privacy, permissions, approval, history, recurrence, reminders, and cascades passed.');

// Exercise the same SQL projection and mutation adapter used by the staging app.
const ts=require('typescript');
const js=ts.transpileModule(read('src/lib/postgres/query.ts'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {Query}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
await as(owner);
const project=(await rows("SELECT create_workspace_project('Adapter QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
const run=async fn=>{await db.exec('BEGIN');try{const value=await fn(db);await db.exec('COMMIT');return value;}catch(e){await db.exec('ROLLBACK');throw e;}};
const q=table=>new Query(table,run);
const inserted=await q('tasks').insert({project_id:project,title:'Adapter task',assignee_id:member,created_by:owner}).select('id').single().execute();
assert.equal(inserted.error,null);const task=inserted.data.id;
await q('task_comments').insert({task_id:task,author_id:owner,content:'Remark'}).execute();
const result=await q('tasks').select('*, assignee:profiles!tasks_assignee_id_fkey(id,full_name,email),task_comments(*,author:profiles!task_comments_author_id_fkey(id,full_name,email))').eq('id',task).single().execute();
assert.equal(result.error,null);assert.equal(result.data.assignee.id,member);assert.equal(result.data.task_comments[0].author.id,owner);
const cards=await q('projects').select('id,project_members(count),tasks(id,status,due_date)').eq('id',project).single().execute();
assert.equal(cards.error,null);assert.equal(cards.data.project_members[0].count,2);assert.equal(cards.data.tasks[0].id,task);
assert.equal((await q('tasks').select('id,project:projects!inner(is_archived)').eq('project.is_archived',false).execute()).data.length,1);
await as(member);
assert.ok((await q('tasks').update({title:'Forbidden'}).eq('id',task).select('id').single().execute()).error);
assert.equal((await q('tasks').update({status:'in_review'}).eq('id',task).select('id').single().execute()).error,null);
await as(outsider);
assert.equal((await q('tasks').select('*').eq('id',task).execute()).data.length,0);
await as(member);
const notifications=await q('notifications').select('*',{head:true,count:'exact'}).eq('user_id',member).eq('is_read',false).execute();
assert.ok(notifications.count>=1);assert.equal(notifications.data,null);
assert.equal((await q('notifications').update({is_read:true}).eq('user_id',member).execute()).error,null);
assert.ok((await q('notifications').update({user_id:outsider}).eq('user_id',member).execute()).error);
assert.throws(()=>q('auth.users'));
assert.ok((await q('profiles').select('id); DROP TABLE profiles;--').execute()).error);
await as(owner);
assert.equal((await q('tasks').update({title:"Robert'); DROP TABLE tasks;--"}).eq('id',task).select('title').single().execute()).data.title,"Robert'); DROP TABLE tasks;--");
await as(null);await db.exec('SET ROLE tasktracker_runtime');
assert.equal((await rows("SELECT rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user"))[0].rolsuper,false);
await assert.rejects(()=>rows('SELECT * FROM profiles'));
await rows("INSERT INTO auth.sessions(token_hash,user_id,expires_at) VALUES('synthetic-token',$1,now()+interval '1 hour')",[owner]);
await rows("DELETE FROM auth.sessions WHERE token_hash='synthetic-token'");
console.log('SQL adapter: nested data, counts, mutation checks, notifications, injection handling, and runtime role passed.');
await db.close();
