import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const { PGlite }=require(process.env.PGLITE_PATH || '@electric-sql/pglite');
process.on('uncaughtException', e => { console.error(e.stack, e.where || ''); process.exit(1); });
const db=new PGlite();
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
for(const f of ['001_base.sql','002_review.sql','003_workspace.sql','004_automation.sql','005_runtime.sql','006_archiving.sql'])await db.exec(read('postgres/'+f));
const admin='00000000-0000-0000-0000-000000000001',owner='00000000-0000-0000-0000-000000000002',member='00000000-0000-0000-0000-000000000003',outsider='00000000-0000-0000-0000-000000000004';
for(const [id,role] of [[admin,'admin'],[owner,'member'],[member,'member'],[outsider,'member']]){
 await db.query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[id,id+'@collegedunia.com']);
 await db.query('INSERT INTO profiles(id,email,full_name,role) VALUES($1,$2,$3,$4)',[id,id+'@collegedunia.com',role,role]);
}
async function as(id){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id || '']);if(id)await db.exec('SET ROLE authenticated');}
async function rows(sql,args=[]){return (await db.query(sql,args)).rows;}
await as(owner);
const p=(await rows("SELECT create_workspace_project('Private QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
assert.equal((await rows('SELECT * FROM project_members WHERE project_id=$1',[p])).length,2);
const t=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Owner task',$2,$3) RETURNING id",[p,owner,member]))[0].id;
await as(outsider);assert.equal((await rows('SELECT * FROM projects WHERE id=$1',[p])).length,0);
await assert.rejects(()=>rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Forbidden',$2)",[p,outsider]));
await as(member);
assert.equal((await rows("UPDATE profiles SET role='admin' WHERE id=$1 RETURNING id",[member])).length,0);
await assert.rejects(()=>rows("UPDATE tasks SET title='Hijack' WHERE id=$1",[t]));
await rows("UPDATE tasks SET status='in_progress' WHERE id=$1",[t]);
await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await rows("UPDATE tasks SET status='in_review' WHERE id=$1",[t]);
await as(owner);await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await as(member);
const own=(await rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Member own task',$2) RETURNING id",[p,member]))[0].id;
await rows("UPDATE tasks SET title='Edited own task' WHERE id=$1",[own]);
const checklist=(await rows("INSERT INTO task_checklist(task_id,title) VALUES($1,'Check result') RETURNING id",[t]))[0].id;
await as(admin);await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[t]));
await rows('UPDATE task_checklist SET completed=true WHERE id=$1',[checklist]);await rows("UPDATE tasks SET status='done' WHERE id=$1",[t]);
await as(owner);
await assert.rejects(()=>rows("INSERT INTO task_checklist(task_id,title) VALUES($1,'Late item')",[t]));
await assert.rejects(()=>rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[t,own]));
await rows("UPDATE tasks SET status='todo' WHERE id=$1",[t]);
await rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[t,own]);
await as(member);await assert.rejects(()=>rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[own,t]));
await assert.rejects(()=>rows('SELECT run_workspace_automation()'));
await as(admin);await rows('DELETE FROM task_dependencies WHERE task_id=$1',[t]);
await as(owner);
const recurring=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date,recurrence) VALUES($1,'Repeat QA',$2,$3,(now() AT TIME ZONE 'Asia/Kolkata')::date-1,'daily') RETURNING id",[p,owner,member]))[0].id;
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');
assert.equal((await rows('SELECT * FROM tasks WHERE recurrence_source=$1',[recurring])).length,1);
const counts=await rows('SELECT dedupe_key,count(*) n FROM notifications WHERE dedupe_key IS NOT NULL GROUP BY dedupe_key HAVING count(*)>1');assert.equal(counts.length,0);
assert.equal((await rows("SELECT next_task_date('2026-02-28','monthly','2026-01-31')::text d"))[0].d,'2026-03-31');
await as(owner);assert.ok((await rows('SELECT * FROM task_history WHERE task_id=$1',[t])).length>=4);
await assert.rejects(()=>rows("INSERT INTO task_history(task_id,field) VALUES($1,'fake')",[t]));
await as(member);await rows('DELETE FROM tasks WHERE id=$1',[own]);
await as(owner);await rows('UPDATE projects SET is_private=false WHERE id=$1',[p]);
await as(outsider);assert.equal((await rows('SELECT * FROM projects WHERE id=$1',[p])).length,1);
await assert.rejects(()=>rows("INSERT INTO tasks(project_id,title,created_by) VALUES($1,'Read only',$2)",[p,outsider]));
await as(owner);await rows('DELETE FROM projects WHERE id=$1',[p]);
await as(null);assert.equal((await rows('SELECT * FROM tasks WHERE project_id=$1',[p])).length,0);
console.log('Standalone schema: privacy, permissions, approval, history, recurrence, reminders, and cascades passed.');

// Exercise the same SQL projection and mutation adapter used by the staging app.
const ts=require('typescript');
const js=ts.transpileModule(read('src/lib/postgres/query.ts'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {Query}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
await as(owner);
const project=(await rows("SELECT create_workspace_project('Adapter QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
const run=async fn=>{await db.exec('BEGIN');try{const value=await fn(db);await db.exec('COMMIT');return value;}catch(e){await db.exec('ROLLBACK');throw e;}};
const q=table=>new Query(table,run);
const inserted=await q('tasks').insert({project_id:project,title:'Adapter task',assignee_id:member,created_by:owner}).select('id').single().execute();
assert.equal(inserted.error,null);const task=inserted.data.id;
await q('task_comments').insert({task_id:task,author_id:owner,content:'Remark'}).execute();
const result=await q('tasks').select('*, assignee:profiles!tasks_assignee_id_fkey(id,full_name,email),task_comments(*,author:profiles!task_comments_author_id_fkey(id,full_name,email))').eq('id',task).single().execute();
assert.equal(result.error,null);assert.equal(result.data.assignee.id,member);assert.equal(result.data.task_comments[0].author.id,owner);
const cards=await q('projects').select('id,project_members(count),tasks(id,status,due_date)').eq('id',project).single().execute();
assert.equal(cards.error,null);assert.equal(cards.data.project_members[0].count,2);assert.equal(cards.data.tasks[0].id,task);
assert.equal((await q('tasks').select('id,project:projects!inner(is_archived)').eq('project.is_archived',false).execute()).data.length,1);
await as(member);
assert.ok((await q('tasks').update({title:'Forbidden'}).eq('id',task).select('id').single().execute()).error);
assert.equal((await q('tasks').update({status:'in_review'}).eq('id',task).select('id').single().execute()).error,null);
await as(outsider);
assert.equal((await q('tasks').select('*').eq('id',task).execute()).data.length,0);
await as(member);
const notifications=await q('notifications').select('*',{head:true,count:'exact'}).eq('user_id',member).eq('is_read',false).execute();
assert.ok(notifications.count>=1);assert.equal(notifications.data,null);
assert.equal((await q('notifications').update({is_read:true}).eq('user_id',member).execute()).error,null);
assert.ok((await q('notifications').update({user_id:outsider}).eq('user_id',member).execute()).error);
assert.throws(()=>q('auth.users'));
assert.ok((await q('profiles').select('id); DROP TABLE profiles;--').execute()).error);
await as(owner);
assert.equal((await q('tasks').update({title:"Robert'); DROP TABLE tasks;--"}).eq('id',task).select('title').single().execute()).data.title,"Robert'); DROP TABLE tasks;--");
await as(null);await db.exec('SET ROLE tasktracker_runtime');
assert.equal((await rows("SELECT rolsuper,rolbypassrls FROM pg_roles WHERE rolname=current_user"))[0].rolsuper,false);
await assert.rejects(()=>rows('SELECT * FROM profiles'));
await rows("INSERT INTO auth.sessions(token_hash,user_id,expires_at) VALUES('synthetic-token',$1,now()+interval '1 hour')",[owner]);
await rows("DELETE FROM auth.sessions WHERE token_hash='synthetic-token'");
console.log('SQL adapter: nested data, counts, mutation checks, notifications, injection handling, and runtime role passed.');

await as(owner);
const ap=(await rows("SELECT create_workspace_project('Archive QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
const at=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Archive task',$2,$3) RETURNING id",[ap,owner,member]))[0].id;
await assert.rejects(()=>rows("SELECT set_archive('task',$1,true,false,false)",[at]));
await assert.rejects(()=>rows("SELECT set_archive('project',$1,true,false,true)",[ap]));
await as(admin);await rows("UPDATE tasks SET status='done' WHERE id=$1",[at]);
await as(member);await assert.rejects(()=>rows("SELECT set_archive('task',$1,true,false,false)",[at]));
await assert.rejects(()=>rows('SELECT run_archive_automation()'));
assert.equal((await rows('UPDATE archive_settings SET task_days=1 WHERE id=true RETURNING id')).length,0);
await as(owner);await rows("SELECT set_archive('task',$1,true,false,false)",[at]);
assert.equal((await rows('SELECT is_archived FROM tasks WHERE id=$1',[at]))[0].is_archived,true);
assert.equal((await rows('UPDATE tasks SET title=title WHERE id=$1 RETURNING id',[at])).length,0);
await assert.rejects(()=>rows("INSERT INTO task_comments(task_id,author_id,content) VALUES($1,$2,'blocked')",[at,owner]));
await rows("SELECT set_archive('project',$1,true,false,true)",[ap]);
assert.ok((await rows('SELECT completed_at FROM projects WHERE id=$1',[ap]))[0].completed_at);
await as(member);assert.equal((await rows('SELECT id FROM projects WHERE id=$1',[ap])).length,1);
await as(outsider);assert.equal((await rows('SELECT id FROM projects WHERE id=$1',[ap])).length,0);
await as(owner);await assert.rejects(()=>rows("SELECT set_archive('task',$1,false,false,false)",[at]));
await rows("SELECT set_archive('project',$1,false,false,false)",[ap]);
assert.equal((await rows('SELECT is_archived FROM tasks WHERE id=$1',[at]))[0].is_archived,true);
await rows("SELECT set_archive('task',$1,false,false,false)",[at]);
await as(null);await rows("UPDATE tasks SET completed_at=now()-interval '40 days',restored_at=NULL WHERE id=$1",[at]);
await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');
assert.equal((await rows('SELECT is_archived FROM tasks WHERE id=$1',[at]))[0].is_archived,true);
await as(owner);await rows("SELECT set_archive('task',$1,false,false,false)",[at]);
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');
assert.equal((await rows('SELECT is_archived FROM tasks WHERE id=$1',[at]))[0].is_archived,false);
await as(null);await rows("UPDATE tasks SET completed_at=now()-interval '100 days',restored_at=NULL WHERE id=$1",[at]);
await rows("UPDATE projects SET restored_at=NULL WHERE id=$1",[ap]);
await db.exec('ALTER TABLE projects DISABLE TRIGGER zz_updated_at');
await rows("UPDATE projects SET updated_at=now()-interval '100 days' WHERE id=$1",[ap]);
await db.exec('ALTER TABLE projects ENABLE TRIGGER zz_updated_at; SET ROLE service_role');
await rows('SELECT run_workspace_automation()');
assert.equal((await rows('SELECT is_archived FROM projects WHERE id=$1',[ap]))[0].is_archived,true);
assert.equal((await rows('SELECT completed_at FROM projects WHERE id=$1',[ap]))[0].completed_at,null);
console.log('Archiving: ownership, privacy, read-only tasks, completion validation, restore, retention, automatic tasks/projects and retry safety passed.');
await as(null);const originalProfiles=await rows('SELECT to_jsonb(p) data FROM profiles p ORDER BY id');await db.exec(read('postgres/007_people_review.sql'));
assert.deepEqual(await rows("SELECT to_jsonb(p)-'is_active' data FROM profiles p ORDER BY id"),originalProfiles);
await as(admin);await rows('SELECT set_review_policy(true)');
await as(owner);
const rp=(await rows("SELECT create_workspace_project('Review lifecycle QA','',ARRAY[$1::uuid,$2::uuid],true) id",[member,admin]))[0].id;
const rt=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Delegated work',$2,$3) RETURNING id",[rp,owner,member]))[0].id;
const version=async()=>Number((await rows('SELECT review_version FROM tasks WHERE id=$1',[rt]))[0].review_version);
const review=async(action,reason='',v=null)=>rows('SELECT review_task($1,$2,$3,$4)',[rt,v??await version(),action,reason]);
await as(member);await assert.rejects(()=>rows("UPDATE tasks SET status='in_review' WHERE id=$1",[rt]));await review('submit');
await assert.rejects(()=>review('approve'));
await as(owner);await assert.rejects(()=>review('changes'));await review('changes','Please attach the result');
await as(member);await review('submit');
await as(owner);const oldVersion=await version();await rows("UPDATE tasks SET priority='high' WHERE id=$1",[rt]);
assert.equal((await rows('SELECT status FROM tasks WHERE id=$1',[rt]))[0].status,'in_progress');
await assert.rejects(()=>review('approve','',oldVersion));
await as(member);await review('submit');await assert.rejects(()=>rows("INSERT INTO task_checklist(task_id,title) VALUES($1,'Late check')",[rt]));
await as(owner);await review('approve');assert.equal((await rows('SELECT status FROM tasks WHERE id=$1',[rt]))[0].status,'done');
await assert.rejects(()=>rows("UPDATE tasks SET title='Changed' WHERE id=$1",[rt]));await assert.rejects(()=>review('reopen'));await review('reopen','Additional work');
await as(admin);await rows('UPDATE tasks SET assignee_id=$1 WHERE id=$2',[admin,rt]);await review('submit');await assert.rejects(()=>review('approve'));
await rows('SELECT set_review_policy(false)');await assert.rejects(()=>rows("UPDATE tasks SET status='done' WHERE id=$1",[rt]));await rows('SELECT set_review_policy(true)');
await as(owner);await review('approve');await review('reopen','Reassign work');
await as(admin);await rows('UPDATE tasks SET assignee_id=$1 WHERE id=$2',[member,rt]);
const heldSource=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date,recurrence) VALUES($1,'Inactive recurrence QA',$2,$3,(now() AT TIME ZONE 'Asia/Kolkata')::date-1,'daily') RETURNING id",[rp,admin,member]))[0].id;
await as(null);await rows("INSERT INTO auth.sessions(token_hash,user_id,expires_at) VALUES('r3-synthetic',$1,now()+interval '1 hour')",[member]);
await as(admin);await rows("SELECT set_member_active($1,false,'Departed team')",[member]);
assert.equal((await rows('SELECT is_active FROM profiles WHERE id=$1',[member]))[0].is_active,false);
await as(null);assert.equal((await rows('SELECT * FROM auth.sessions WHERE user_id=$1',[member])).length,0);
await as(member);assert.equal((await rows('SELECT * FROM tasks')).length,0);await assert.rejects(()=>review('submit','',0));
await as(admin);await assert.rejects(()=>rows('SELECT set_member_active($1,false,$2)',[admin,'Self']));
await assert.rejects(()=>rows("UPDATE profiles SET role='member' WHERE id=$1",[admin]));
await assert.rejects(()=>rows("INSERT INTO tasks(project_id,title,created_by,assignee_id) VALUES($1,'Inactive target',$2,$3)",[rp,admin,member]));
await assert.rejects(()=>rows('SELECT reassign_member_tasks($1,$2,$3,$4)',[member,rp,owner,'[]']));
await as(null);const held=(await rows('SELECT next_occurrence::text FROM tasks WHERE id=$1',[heldSource]))[0].next_occurrence;const notices=(await rows('SELECT count(*) FROM notifications WHERE user_id=$1',[member]))[0].count;await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');assert.equal((await rows('SELECT next_occurrence::text FROM tasks WHERE id=$1',[heldSource]))[0].next_occurrence,held);assert.equal((await rows('SELECT count(*) FROM notifications WHERE user_id=$1',[member]))[0].count,notices);
assert.equal((await rows('SELECT count(*) FROM tasks WHERE recurrence_source=$1',[heldSource]))[0].count,0);await as(admin);
const preview=await rows("SELECT id,review_version::int version FROM tasks WHERE project_id=$1 AND assignee_id=$2 AND status<>'done' AND NOT is_archived ORDER BY id",[rp,member]);
await rows('SELECT reassign_member_tasks($1,$2,$3,$4)',[member,rp,owner,JSON.stringify(preview)]);
assert.equal((await rows('SELECT created_by,assignee_id FROM tasks WHERE id=$1',[rt]))[0].created_by,owner);
assert.equal((await rows('SELECT assignee_id FROM tasks WHERE id=$1',[rt]))[0].assignee_id,owner);

await as(admin);await rows("SELECT set_member_active($1,true,'Returned to team')",[member]);
await as(member);assert.ok((await rows('SELECT * FROM tasks WHERE id=$1',[rt])).length);
await as(admin);assert.ok((await rows('SELECT * FROM member_events WHERE member_id=$1',[member])).length>=3);
await as(null);await db.exec('SET SESSION AUTHORIZATION tasktracker_runtime');await assert.rejects(()=>rows('DELETE FROM auth.users WHERE id=$1',[member]));await db.exec('SET SESSION AUTHORIZATION postgres');
console.log('Release 3: creator review, no self-approval, stale decisions, required reasons, immutable submissions, lifecycle/session revocation, inactive RLS, protected admins, and reassignment passed.');

await as(null);await db.exec(read('postgres/008_reporting_collaboration.sql'));await db.exec(read('postgres/011_workspace_preferences.sql'));
await as(owner);
const comment=(await rows("INSERT INTO task_comments(task_id,author_id,content,mentions) VALUES($1,$2,'Please inspect this result',ARRAY[$3::uuid]) RETURNING id",[rt,owner,member]))[0].id;
await assert.rejects(()=>rows('UPDATE task_comments SET mentions=ARRAY[$1::uuid] WHERE id=$2',[outsider,comment]));
await rows("UPDATE task_comments SET content='Revised remark' WHERE id=$1 AND edit_version=0",[comment]);
assert.equal((await rows('SELECT * FROM remark_edits WHERE comment_id=$1',[comment])).length,1);
assert.equal((await rows("UPDATE task_comments SET content='Stale overwrite' WHERE id=$1 AND edit_version=0 RETURNING id",[comment])).length,0);
await as(member);assert.equal((await rows("UPDATE task_comments SET content='Not mine' WHERE id=$1 RETURNING id",[comment])).length,0);
assert.equal((await rows("SELECT * FROM notifications WHERE user_id=$1 AND dedupe_key LIKE 'mention:%'",[member])).length,1);
await as(outsider);assert.equal((await rows('SELECT * FROM remark_edits WHERE comment_id=$1',[comment])).length,0);
await as(owner);await review('submit');await as(admin);await review('approve');
const fact=(await rows("SELECT * FROM completion_events WHERE task_id=$1 AND source='approval'",[rt]))[0];assert.equal(fact.assignee_id,owner);assert.equal(fact.source,'approval');
const completionCount=(await rows('SELECT * FROM completion_events WHERE task_id=$1',[rt])).length;await rows("SELECT set_archive('task',$1,true,false,false)",[rt]);assert.equal((await rows('SELECT * FROM completion_events WHERE task_id=$1',[rt])).length,completionCount);
await as(outsider);assert.equal((await rows('SELECT * FROM completion_events WHERE task_id=$1',[rt])).length,0);
await as(owner);
const scheduleTask=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_id,due_date,recurrence) VALUES($1,'Original recurring title',$2,$3,(now() AT TIME ZONE 'Asia/Kolkata')::date-1,'daily') RETURNING id",[rp,owner,member]))[0].id;
await rows("SELECT save_task_schedule($1,0,'Future title','Future instructions','high',$2,'daily',(now() AT TIME ZONE 'Asia/Kolkata')::date,NULL,true)",[scheduleTask,member]);
assert.equal((await rows('SELECT title FROM tasks WHERE id=$1',[scheduleTask]))[0].title,'Original recurring title');
await assert.rejects(()=>rows("SELECT save_task_schedule($1,0,'Stale schedule','','high',$2,'daily',current_date+1,NULL,false)",[scheduleTask,member]));
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');assert.equal((await rows('SELECT * FROM tasks WHERE recurrence_source=$1',[scheduleTask])).length,0);
await as(null);await rows('UPDATE task_schedules SET paused=false,end_date=next_run WHERE task_id=$1',[scheduleTask]);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');
const occurrences=await rows('SELECT * FROM tasks WHERE recurrence_source=$1',[scheduleTask]);assert.equal(occurrences.length,1);assert.equal(occurrences[0].title,'Future title');
await as(owner);await assert.rejects(()=>rows("UPDATE tasks SET recurrence='weekly' WHERE id=$1",[scheduleTask]));
await as(outsider);assert.equal((await rows('SELECT * FROM task_schedules WHERE task_id=$1',[scheduleTask])).length,0);await assert.rejects(()=>rows("SELECT save_task_schedule($1,2,'Forbidden','','low',NULL,'daily',current_date+1,NULL,false)",[scheduleTask]));
console.log('Release 4 database: versioned remarks, mention validation/deduplication, private edit history, approval snapshots, archived reporting, future-only schedules, pause/end dates, recurrence retry safety and privacy passed.');

await as(null);await db.exec(read('postgres/009_shared_assignments.sql'));
const dataExports={};let dataActor=admin;
new Function('exports','require',ts.transpileModule(read('src/lib/workspace-data.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(dataExports,name=>{
 if(name==='server-only')return {};if(name==='./postgres/auth')return {currentUser:async()=>({id:dataActor})};if(name==='./postgres/db')return {transaction:async(id,work)=>{await as(id);return work(db);}};throw new Error('Unexpected dependency '+name);
});
const report=await dataExports.reportData({from:'2020-01-01',to:'2029-12-31'});assert.ok(report.items.length);assert.ok(report.trend.length);assert.ok(report.items.some(x=>x.task_id===rt&&x.archived));
dataActor=outsider;assert.equal((await dataExports.reportData({from:'2020-01-01',to:'2029-12-31'})).total,0);
dataActor=admin;assert.ok((await dataExports.searchWorkspace('Revised',true)).items.length);dataActor=outsider;assert.equal((await dataExports.searchWorkspace('Revised',true)).total,0);
await as(owner);await rows("INSERT INTO tasks(project_id,title,created_by) SELECT $1,'Scale check '||lpad(n::text,4,'0'),$2 FROM generate_series(1,1000)n",[rp,owner]);
dataActor=owner;const scalePage=await dataExports.taskPage({q:'Scale check',sort:'title'});assert.equal(scalePage.total,1000);assert.equal(scalePage.items.length,25);const scaleNext=await dataExports.taskPage({q:'Scale check',sort:'title',page:2});assert.equal(scaleNext.items.length,25);assert.ok(!scaleNext.items.some(t=>scalePage.items.some(x=>x.id===t.id)));assert.equal((await dataExports.taskPage({q:'Scale check'},true)).items.length,1000);dataActor=outsider;assert.equal((await dataExports.taskPage({q:'Scale check'})).total,0);
console.log('Release 4 query integration: actual report/trend SQL, archived completion visibility, full-text search privacy, 1,000 rows with stable pages and complete exports passed.');

await as(owner);const mp=(await rows("SELECT create_workspace_project('Shared assignment QA','',ARRAY[$1::uuid,$2::uuid],true) id",[member,admin]))[0].id;
const mt=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_ids,due_date) VALUES($1,'Shared task',$2,ARRAY[$2::uuid,$3::uuid],current_date-1) RETURNING id",[mp,owner,member]))[0].id;
await assert.rejects(()=>rows('UPDATE tasks SET assignee_ids=ARRAY[$1::uuid] WHERE id=$2',[outsider,mt]));
await as(member);await rows("UPDATE tasks SET status='in_progress' WHERE id=$1",[mt]);await assert.rejects(()=>rows("UPDATE tasks SET title='Forbidden edit' WHERE id=$1",[mt]));
dataActor=member;assert.ok((await dataExports.taskPage({mine:true})).items.some(t=>t.id===mt));
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');
assert.equal((await rows("SELECT user_id FROM notifications WHERE task_id=$1 AND dedupe_key LIKE '%:deadline'",[mt])).length,2);
await as(member);let mv=(await rows('SELECT review_version FROM tasks WHERE id=$1',[mt]))[0].review_version;await rows("SELECT review_task($1,$2,'submit','')",[mt,mv]);
await as(owner);mv=(await rows('SELECT review_version FROM tasks WHERE id=$1',[mt]))[0].review_version;await assert.rejects(()=>rows("SELECT review_task($1,$2,'approve','')",[mt,mv]));
await as(admin);await rows("SELECT review_task($1,$2,'approve','')",[mt,mv]);const mf=(await rows('SELECT assignee_ids FROM completion_events WHERE task_id=$1',[mt]))[0];assert.deepEqual(mf.assignee_ids,[owner,member]);
await as(owner);const sharedAdminTask=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_ids) VALUES($1,'Assigned admin cannot approve',$2,ARRAY[$3::uuid,$4::uuid]) RETURNING id",[mp,owner,member,admin]))[0].id;
await as(member);await rows("SELECT review_task($1,0,'submit','')",[sharedAdminTask]);await as(admin);await assert.rejects(()=>rows("SELECT review_task($1,1,'approve','')",[sharedAdminTask]));await as(owner);await rows("SELECT review_task($1,1,'approve','')",[sharedAdminTask]);
const recur=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_ids,due_date,recurrence) VALUES($1,'Shared repeating task',$2,ARRAY[$2::uuid,$3::uuid],current_date-1,'daily') RETURNING id",[mp,owner,member]))[0].id;
await as(null);await db.exec('SET ROLE service_role');await rows('SELECT run_workspace_automation()');await rows('SELECT run_workspace_automation()');assert.deepEqual((await rows('SELECT assignee_ids FROM tasks WHERE recurrence_source=$1 LIMIT 1',[recur]))[0].assignee_ids,[owner,member]);
await as(owner);await rows('SELECT remove_member_and_reassign_tasks($1,$2,$3)',[mp,member,admin]);assert.deepEqual((await rows('SELECT assignee_ids FROM tasks WHERE id=$1',[recur]))[0].assignee_ids,[owner,admin]);
console.log('Shared assignment: co-assignee status/submission, creator/admin self-approval denial, per-person My Tasks/reminders, immutable completion group, repeating groups, private assignment validation and member replacement passed.');


// Release 5: run the actual planning implementation under the authenticated RLS role.
await as(null);await db.exec(read('postgres/010_planning.sql'));
const planTypes={},planning={};
new Function('exports',ts.transpileModule(read('src/lib/planning-types.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(planTypes);
let planActor=owner;
new Function('exports','require',ts.transpileModule(read('src/lib/planning.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(planning,name=>{
 if(name==='server-only')return {};if(name==='node:crypto')return require('node:crypto');if(name==='./planning-types')return planTypes;
 if(name==='./workspace-data')return {workspaceRead:async work=>{await as(planActor);return run(async()=>{await rows('SELECT assert_active()');return work(db,planActor);});}};throw Error(name);
});
await as(owner);const pp=(await rows("SELECT create_workspace_project('Planning original','Project description',ARRAY[$1::uuid],true) id",[member]))[0].id;
const pt1=(await rows("INSERT INTO tasks(project_id,title,description,created_by,assignee_ids,due_date,priority) VALUES($1,'Planning first','First description',$2,ARRAY[$2::uuid,$3::uuid],'2026-01-01','high') RETURNING id",[pp,owner,member]))[0].id;
const pt2=(await rows("INSERT INTO tasks(project_id,title,created_by,due_date) VALUES($1,'Planning next',$2,'2026-01-04') RETURNING id",[pp,owner]))[0].id;
await rows("INSERT INTO task_checklist(task_id,title,completed) VALUES($1,'Reusable checklist',true)",[pt1]);await rows('INSERT INTO task_dependencies(task_id,depends_on) VALUES($1,$2)',[pt2,pt1]);
const ps={kind:'project',id:pp};const pv=await planning.previewPlanning(ps);assert.deepEqual(pv.blueprint.tasks.map(t=>t.offset),[0,3]);
const template=await planning.storeTemplate(ps,pv.version,'Personal repeat');
planActor=member;assert.equal((await planning.planningOptions()).templates.length,0);await assert.rejects(()=>planning.previewPlanning({kind:'template',id:template.id}));
planActor=outsider;await assert.rejects(()=>planning.previewPlanning(ps));await assert.rejects(()=>planning.storeTemplate(ps,pv.version,'Forbidden'));
planActor=owner;const makeInput=preview=>({source:preview.source,version:preview.version,requestId:require('node:crypto').randomUUID(),name:'Planning copy',description:'Fresh work',targetProjectId:pp,members:[member],tasks:preview.blueprint.tasks.map(t=>({key:t.key,title:t.title,description:t.description,priority:t.priority,dueDate:t.offset===null?'':planTypes.shiftDate('2026-09-20',t.offset),assigneeIds:[owner,member],checklist:t.checklist}))});
const pi=makeInput(pv),copy=await planning.createPlan(pi);assert.deepEqual(await planning.createPlan(pi),copy);await assert.rejects(()=>planning.createPlan({...pi,name:'Changed retry'}));
await as(owner);const copied=await rows('SELECT * FROM tasks WHERE project_id=$1 ORDER BY due_date',[copy.projectId]);assert.equal(copied.length,2);assert.ok(copied.every(t=>t.status==='todo'&&t.created_by===owner&&t.recurrence==='none'));assert.deepEqual(copied.map(t=>new Date(t.due_date).toISOString().slice(0,10)),['2026-09-20','2026-09-23']);assert.deepEqual(copied[0].assignee_ids,[owner,member]);assert.equal((await rows('SELECT completed FROM task_checklist WHERE task_id=$1',[copied[0].id]))[0].completed,false);assert.equal((await rows('SELECT depends_on FROM task_dependencies WHERE task_id=$1',[copied[1].id]))[0].depends_on,copied[0].id);
assert.equal((await rows('SELECT is_private FROM projects WHERE id=$1',[copy.projectId]))[0].is_private,true);
const before=Number((await rows('SELECT count(*) n FROM projects'))[0].n);
const invalid=makeInput(pv);invalid.tasks[1].assigneeIds=[outsider];await assert.rejects(()=>planning.createPlan(invalid));await as(owner);assert.equal(Number((await rows('SELECT count(*) n FROM projects'))[0].n),before);
await rows("UPDATE tasks SET title='Source changed' WHERE id=$1",[pt1]);await assert.rejects(()=>planning.createPlan(makeInput(pv)),/source changed/i);
const stored=await planning.previewPlanning({kind:'template',id:template.id});assert.equal(stored.blueprint.tasks[0].title,'Planning first');
const tp=await planning.previewPlanning({kind:'task',id:pt2});assert.equal(tp.blueprint.tasks[0].dependencies.length,0);const ti=makeInput(tp);ti.name='Single new task';const one=await planning.createPlan(ti);assert.ok(one.taskId);assert.equal(one.projectId,pp);
const cal=await planning.calendarData('2026-09-20','month',copy.projectId,member);assert.equal(cal.total,2);assert.equal(cal.items.length,2);assert.equal(new Set(cal.items.map(t=>t.id)).size,2);
planActor=outsider;assert.equal((await planning.calendarData('2026-09-20','month',copy.projectId,'')).total,0);assert.equal((await planning.calendarData('2026-09-20','month',copy.projectId,'')).undated,0);
planActor=member;const memberPreview=await planning.previewPlanning(ps),memberTemplate=await planning.storeTemplate(ps,memberPreview.version,'Member own template');
await as(owner);await rows('SELECT remove_member_and_reassign_tasks($1,$2,$3)',[pp,member,owner]);await assert.rejects(()=>planning.previewPlanning({kind:'template',id:memberTemplate.id}));
planActor=owner;await planning.removeTemplate(template.id);await assert.rejects(()=>planning.previewPlanning({kind:'template',id:template.id}));
await assert.rejects(()=>planning.previewPlanning({kind:'project',id:rp}),/100 active tasks/);
await as(admin);await rows("SELECT set_member_active($1,false,'Planning inactive test')",[member]);planActor=member;await assert.rejects(()=>planning.planningOptions(),/inactive/i);await as(admin);await rows("SELECT set_member_active($1,true,'Planning test complete')",[member]);
console.log('Release 5: private templates, revoked/inactive access, date shifting, shared assignments, unchecked checklists, dependency remapping, source-version validation, atomic invalid-copy rollback, idempotent retries and private calendar passed.');


// Release A: exercise the actual save helper under database row-level security.
await as(admin);
const remarkProject=(await rows("SELECT create_workspace_project('Save reliability QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
const remarkTask=(await rows("INSERT INTO tasks(project_id,title,created_by,assignee_ids) VALUES($1,'Save reliability',$2,ARRAY[$3::uuid]) RETURNING id",[remarkProject,admin,member]))[0].id;
const remarkModule={exports:{}};
new Function('exports',require('typescript').transpileModule(read('src/lib/postgres/remarks.ts'),{compilerOptions:{module:require('typescript').ModuleKind.CommonJS,target:require('typescript').ScriptTarget.ES2022}}).outputText)(remarkModule.exports);
const write=remarkModule.exports.writeRemark;
const connection={query:async(sql,args)=>{const result=await db.query(sql,args);return {...result,rowCount:result.affectedRows??result.rows.length};}};
const creatorRow=await q('tasks').select('creator:task_creator(id)').eq('id',remarkTask).single().execute();assert.equal(creatorRow.data.creator.id,admin);
const request='11111111-2222-4333-8444-555555555555';
const first=await write(connection,admin,remarkTask,'Confirmed once',[member],undefined,undefined,request);
const again=await write(connection,admin,remarkTask,'Confirmed once',[member],undefined,undefined,request);
assert.equal(first.id,again.id);
assert.equal((await rows('SELECT id FROM task_comments WHERE id=$1',[request])).length,1);
await as(member);assert.equal((await rows("SELECT id FROM notifications WHERE dedupe_key LIKE $1",['mention:'+request+':%'])).length,1);await as(admin);
const edited=await write(connection,admin,remarkTask,'Edited once',[member],first.id,0);
const retriedEdit=await write(connection,admin,remarkTask,'Edited once',[member],first.id,0);
assert.equal(Number(edited.edit_version),Number(retriedEdit.edit_version));
assert.equal((await rows('SELECT id FROM remark_edits WHERE comment_id=$1',[request])).length,1);
await assert.rejects(()=>write(connection,admin,remarkTask,'Conflicting overwrite',[],first.id,0));
await as(member);await assert.rejects(()=>write(connection,member,remarkTask,'Edited once',[member],undefined,undefined,request));
await as(outsider);await assert.rejects(()=>write(connection,outsider,remarkTask,'Private task',[],undefined,undefined,'11111111-2222-4333-8444-555555555556'));
await as(admin);await rows("SELECT set_archive('project',$1,true,true,false)",[remarkProject]);
await assert.rejects(()=>write(connection,admin,remarkTask,'Archived task',[]));
console.log('Release A: retry-safe creation and edits, one mention notification/history entry, conflict, ownership, privacy and archive checks passed.');

// Release C/D: private settings, notification delivery and actual bulk mutations.
await as(owner);const privateView=(await rows("INSERT INTO saved_task_views(user_id,name,filters) VALUES($1,'Owner review','{\"preset\":\"review\"}') RETURNING id",[owner]))[0].id;
await rows('INSERT INTO notification_preferences(user_id,deadline_days,mentions,assignments,reviews) VALUES($1,0,false,false,false)',[owner]);
await as(outsider);assert.equal((await rows('SELECT * FROM saved_task_views WHERE id=$1',[privateView])).length,0);assert.equal((await rows('SELECT * FROM notification_preferences WHERE user_id=$1',[owner])).length,0);
await assert.rejects(()=>rows("INSERT INTO saved_task_views(user_id,name,filters) VALUES($1,'Stolen','{}')",[owner]));
await as(owner);
const bulkProject=(await rows("SELECT create_workspace_project('Bulk QA','',ARRAY[$1::uuid],true) id",[member]))[0].id;
const bulkIds=[];for(const title of ['Editable','Submitted','Completed'])bulkIds.push((await rows("INSERT INTO tasks(project_id,title,created_by,assignee_ids) VALUES($1,$2,$3,ARRAY[$4::uuid]) RETURNING id",[bulkProject,title,owner,member]))[0].id);
await as(member);for(const task of bulkIds.slice(1))await rows("SELECT review_task($1,0,'submit','')",[task]);
await as(owner);await rows("SELECT review_task($1,(SELECT review_version FROM tasks WHERE id=$1),'approve','')",[bulkIds[2]]);
const bulkModule={exports:{}};new Function('exports',ts.transpileModule(read('src/lib/postgres/bulk-tasks.ts'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(bulkModule.exports);
const bulk=bulkModule.exports.bulkTasks;
const selections=(await rows('SELECT id,review_version FROM tasks WHERE id=ANY($1::uuid[])',[bulkIds])).map(t=>({id:t.id,version:Number(t.review_version)}));
await db.exec('BEGIN');const cdPreview=await bulk(db,owner,selections,{action:'deadline',deadline:'2026-12-01'});await db.exec('COMMIT');assert.equal(cdPreview.filter(x=>x.eligible).length,1);
await db.exec('BEGIN');const cdApplied=await bulk(db,owner,selections,{action:'deadline',deadline:'2026-12-01'},true);await db.exec('COMMIT');assert.equal(cdApplied.filter(x=>x.eligible).length,1);
await db.exec('BEGIN');const cdReplay=await bulk(db,owner,selections,{action:'deadline',deadline:'2026-12-02'},true);await db.exec('COMMIT');assert.equal(cdReplay.filter(x=>x.eligible).length,0);
const cdLatest=(await rows('SELECT id,review_version FROM tasks WHERE id=$1',[bulkIds[0]])).map(t=>({id:t.id,version:Number(t.review_version)}));
await db.exec('BEGIN');assert.equal((await bulk(db,owner,cdLatest,{action:'assign',assignee_ids:[outsider]},true))[0].eligible,false);await db.exec('COMMIT');
await as(member);await db.exec('BEGIN');assert.equal((await bulk(db,member,cdLatest,{action:'deadline',deadline:'2026-12-03'},true))[0].eligible,false);await db.exec('COMMIT');
await as(outsider);await db.exec('BEGIN');const cdHidden=await bulk(db,outsider,cdLatest,{action:'deadline',deadline:'2026-12-03'},true);await db.exec('COMMIT');assert.equal(cdHidden[0].title,'Unavailable task');
await as(owner);await db.exec('BEGIN');assert.equal((await bulk(db,owner,[selections.find(x=>x.id===bulkIds[2])],{action:'archive'},true))[0].eligible,true);await db.exec('COMMIT');
await as(null);
for(const [title,key] of [['Due today','a:deadline'],['You were mentioned','mention:qa'],['Task assigned',null],['Ready for review','qa-review:owner']])assert.equal((await rows("INSERT INTO notifications(user_id,task_id,title,message,dedupe_key) VALUES($1,$2,$3,'test',$4) RETURNING id",[owner,bulkIds[0],title,key])).length,0);
await as(owner);await rows('UPDATE notification_preferences SET deadline_days=7 WHERE user_id=$1',[owner]);await as(null);
const cdNotice=(await rows("INSERT INTO notifications(user_id,task_id,title,message,dedupe_key) VALUES($1,$2,'Due today','test','first:deadline') RETURNING id",[owner,bulkIds[0]]))[0];assert.ok(cdNotice);
assert.equal((await rows("INSERT INTO notifications(user_id,task_id,title,message,dedupe_key) VALUES($1,$2,'Due today','test','second:deadline') RETURNING id",[owner,bulkIds[0]])).length,0);
await rows("UPDATE notifications SET created_at=now()-interval '8 days' WHERE id=$1",[cdNotice.id]);
assert.equal((await rows("INSERT INTO notifications(user_id,task_id,title,message,dedupe_key) VALUES($1,$2,'Due today','test','third:deadline') RETURNING id",[owner,bulkIds[0]])).length,1);
console.log('Release C/D database: saved-view/settings privacy; bulk cdPreview, partial results, stale versions, immutable review, ownership, private tasks, assignment validation and completed archive; notification opt-out and weekly frequency passed.');
await db.close();
