'use client';
import WorkspaceHeading from '@/components/WorkspaceHeading';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import type {planningOptions} from '@/lib/planning';
import {deletePlanningTemplate} from '../planning/actions';
export default function TemplateLibrary({options}:{options:Awaited<ReturnType<typeof planningOptions>>}){
 const [q,setQ]=useState(''),[project,setProject]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');const router=useRouter();
 const filtered=options.templates.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));
 return <section className="space-y-6"><header><WorkspaceHeading className="text-2xl font-bold">Templates</WorkspaceHeading><p className="mt-2 text-sm text-gray-500">Reuse project plans, tasks and their checklists. Only you can use your templates, while you have access to their original project.</p></header><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-surface p-4"><label className="min-w-0 flex-1 text-sm font-medium">Start from a project<select aria-label="Template source project" value={project} onChange={e=>setProject(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Choose a project</option>{options.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{project&&<Link className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm text-white" href={'/dashboard/planning?kind=project&id='+project+'&save=true'}>Preview project template</Link>}<p className="w-full text-sm text-gray-500">For a task template, open a task and choose Save as template in Task actions.</p></div><label className="block text-sm font-medium">Search templates<input aria-label="Search templates" placeholder="Find a reusable plan…" value={q} onChange={e=>setQ(e.target.value)} className="mt-1 w-full rounded-lg border p-3"/></label>{error&&<p role="alert" className="text-red-600">{error}</p>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map(t=><article key={t.id} className="min-w-0 rounded-xl border bg-surface p-5"><h2 className="break-words text-lg font-semibold">{t.name}</h2><p className="mt-2 text-sm text-gray-500">{t.kind==='project'?'Project':'Task'} template · {t.task_count} tasks</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><Link href={'/dashboard/planning?kind=template&id='+t.id} className="rounded-lg border px-3 py-2 text-sm">Use template</Link><button disabled={!!busy} className="rounded-lg px-3 py-2 text-sm text-red-600" onClick={async()=>{if(!confirm('Delete this template? Existing projects and tasks will stay as they are.'))return;setBusy(t.id);setError('');try{const result=await deletePlanningTemplate(t.id);if(result.error)setError(result.error);else router.refresh();}catch{setError('Could not delete the template. Please retry.');}finally{setBusy('');}}}>{busy===t.id?'Deleting…':'Delete template'}</button></div></article>)}</div>{!filtered.length&&<div className="rounded-xl border bg-surface p-8 text-center"><h2 className="font-semibold">{q?'No matching templates':'No templates yet'}</h2><p className="mt-2 text-sm text-gray-500">Save a project or task you repeat, then review dates and assignees each time you use it.</p></div>}</section>;
}
