import {mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {categories,renderEmail,escapeHtml} from './templates.mjs';
const target=resolve(process.argv[2]||'deliverables/email-previews');await mkdir(target,{recursive:true});
const task={id:'sample-task',projectId:'sample-project',title:'Prepare the September admissions report'};
const data={name:'Aishwarya',task,projectId:'sample-project',projectName:'Admissions · September',assignees:'Ankit Toppo, Aishwarya Naidu',actor:'Riya Sharma',deadline:'18 September 2026',note:'Please include the course-wise breakdown and check the final totals before submitting.'};
const initial=new Set(['assignment','mention','review_requested','approved','changes_requested','review_updated','deadline_digest']);
for(const kind of Object.keys(categories)){
 const sample={...data};
 if(kind==='assignment')delete sample.note;
 if(kind==='mention')sample.note='@Aishwarya — could you verify the admissions totals? The supporting sheet is attached to the task.';
 if(kind==='approved')sample.note='The final figures look good. Thank you for completing the report.';
 if(kind==='review_requested')sample.note='The report and supporting documents are ready. Please review the final version.';
 if(kind==='review_updated')sample.note='The task details changed after submission. Open the task to check whether another review is needed.';
 if(kind==='deadline_changed')sample.previousDeadline='16 September 2026';
 if(kind.endsWith('digest')){delete sample.task;delete sample.assignees;delete sample.actor;delete sample.deadline;delete sample.note;delete sample.projectName;sample.period=kind==='deadline_digest'?'Tuesday, 15 September':'Recent task activity';sample.items=[{title:'Verify course-wise enrolment totals',detail:kind==='deadline_digest'?'2 days overdue · Admissions':'Riya added a remark · Admissions',task},{title:'Prepare the September admissions report',detail:kind==='deadline_digest'?'Due today · Admissions':'Status changed to In progress',task},{title:'Publish the weekly team update',detail:kind==='deadline_digest'?'Due tomorrow · Team operations':'Ankit added a supporting document',task}];}
 if(kind==='project_completed'){delete sample.task;delete sample.assignees;delete sample.deadline;delete sample.note;}
 if(kind==='weekly_report'){delete sample.task;delete sample.projectName;delete sample.assignees;delete sample.deadline;delete sample.note;delete sample.actor;sample.period='7–13 September 2026';sample.stats=[{label:'Completed during the week',value:12},{label:'Pending now',value:8},{label:'Overdue now',value:2},{label:'Awaiting review now',value:3}];}
 const rendered=renderEmail(kind,sample);await writeFile(join(target,kind+'.html'),rendered.html);await writeFile(join(target,kind+'.txt'),rendered.text);
}
await writeFile(join(target,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TaskTracker dark email design review</title><style>body{margin:0;background:#080f1b;color:#f1f6fd;font:15px Arial,sans-serif}header,main{max-width:1000px;margin:auto;padding:24px}h1{font-size:30px}nav{display:flex;flex-wrap:wrap;gap:10px}a,button{color:#8fe2ee}a{padding:10px;border:1px solid #2b3c52;border-radius:8px}section{margin:30px 0}iframe{display:block;border:1px solid #2b3c52;background:#121d2c;width:100%;height:1060px;max-width:720px}button{padding:12px;border:1px solid #2b3c52;border-radius:8px;background:#121d2c;cursor:pointer;margin-right:8px}.note{color:#b3c1d4;line-height:1.6}.preview{overflow:auto}</style><header><h1>TaskTracker dark email design review</h1><p class="note">Synthetic examples only. These previews do not send emails. Initial delivery covers assignments, mentions, review events and a daily deadline summary. The additional categories below are designs for later activation. The provider may append its own unsubscribe footer.</p><nav>${Object.entries(categories).map(([k,v])=>`<a href="#${k}">${escapeHtml(v.label)}</a>`).join('')}</nav><p><button onclick="document.querySelectorAll('iframe').forEach(f=>f.style.width='375px')">Phone · 375px</button><button onclick="document.querySelectorAll('iframe').forEach(f=>f.style.width='100%')">Desktop</button></p></header><main>${Object.entries(categories).map(([k,v])=>`<section id="${k}"><h2>${escapeHtml(v.label)}</h2><p class="note">${initial.has(k)?'Initial notification category':'Additional category — design preview'} · <a href="${k}.txt">Plain text</a> · <a href="${k}.html">Open email</a></p><div class="preview"><iframe title="${escapeHtml(v.label)} email preview" src="${k}.html" loading="lazy"></iframe></div></section>`).join('')}</main></html>`);
console.log(`Prepared ${Object.keys(categories).length} email designs in ${target}`);
