'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react';
import { todayKey } from '@/lib/task-presentation';
import type { DashboardInsights } from '@/lib/dashboard-insights';
const states=[['todo','To do','#e7c677'],['in_progress','In progress','#80d6c4'],['blocked','Blocked','#ed9eb2'],['in_review','In review','#b49aee'],['done','Completed','#679fff']];
const shortDate=(day:string)=>new Date(day+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'});
export default function InsightsPanel(){
 const [day,setDay]=useState(todayKey()),[data,setData]=useState<DashboardInsights|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[projectFilter,setProjectFilter]=useState('all');
 useEffect(()=>{const controller=new AbortController();fetch('/api/dashboard-insights?month='+day.slice(0,7)+'&day='+day,{signal:controller.signal,cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||'Dashboard could not load.');return body;}).then(body=>{setData(body);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[day,retry]);
 const loading=!data;
 const agendaLoading=Boolean(data&&data.day!==day);
 function moveMonth(delta:number){const date=new Date(day+'T12:00:00Z');date.setUTCMonth(date.getUTCMonth()+delta,1);if(date.getUTCFullYear()>=2000&&date.getUTCFullYear()<=2100)setDay(date.toISOString().slice(0,10));}
 const active=data?.projects.filter(p=>!p.is_archived)||[],completed=data?.projects.filter(p=>p.is_archived&&p.completed_at)||[],archived=data?.projects.filter(p=>p.is_archived&&!p.completed_at)||[];
 const attention=active.filter(p=>p.attention),onTrack=active.length-attention.length;
 const projects=(data?.projects||[]).filter(p=>projectFilter==='active'?!p.is_archived:projectFilter==='attention'?!p.is_archived&&p.attention:projectFilter==='completed'?Boolean(p.completed_at)&&p.is_archived:projectFilter==='archived'?p.is_archived&&!p.completed_at:true);
 const total=data?.status.reduce((a,b)=>a+b.count,0)||0,done=data?.status.find(x=>x.status==='done')?.count||0;
 let angle=0;const gradient=states.map(([id,,color])=>{const start=angle;angle+=(data?.status.find(x=>x.status===id)?.count||0)/Math.max(1,total)*100;return `${color} ${start}% ${angle}%`;}).join(',');
 const month=day.slice(0,7),first=new Date(month+'-01T12:00:00Z'),days=new Date(first.getUTCFullYear(),first.getUTCMonth()+1,0).getDate(),offset=(first.getUTCDay()+6)%7;
 return <div className="insights-page"><h1 className="text-2xl font-bold mb-3">Dashboard</h1>
 <div className="insights-toolbar"><p>Central Team Workspace · Your accessible projects</p><div className="flex items-center gap-2"><button type="button" aria-label="Refresh dashboard" className="rounded-full border p-2" onClick={()=>{setError('');setRetry(x=>x+1);}}><RefreshCw className="h-4 w-4"/></button></div></div>
 {error&&<div role="alert" className="rounded-xl border p-5"><p>{error}</p><button type="button" className="mt-3 rounded-full border px-4 py-2" onClick={()=>{setError('');setRetry(x=>x+1);}}>Retry dashboard</button></div>}{loading&&!error?<p role="status" className="py-10">Loading dashboard…</p>:data&&<>
 <section aria-label="Project insights"><h3 className="insights-section-title">Project overview</h3><p className="insights-note">All accessible projects, including archived work. Completion is confirmed by the creator or admin.</p><div className="insights-stats insights-project-stats">{[['all','All projects',data.projects.length],['active','Active',active.length],['attention','Needs attention',attention.length],['completed','Completed projects',completed.length],['archived','Archived',archived.length]].map(([key,label,count])=><button type="button" key={key} className="insights-stat" aria-pressed={projectFilter===key} onClick={()=>setProjectFilter(String(key))}><span>{label}</span><strong>{count}</strong><small>{key==='attention'?'Subset of active projects':'View projects'}</small></button>)}</div>
 <div className="insights-grid"><section className="insights-box"><h3>Project progress</h3><p className="insights-note">Completed / total tasks, including archived tasks · first 12 active projects</p>{active.slice(0,12).map(p=><Link href={'/dashboard/projects/'+p.id} key={p.id} className="insights-progress"><div><span>{p.name}</span><b>{p.done}/{p.total} · {p.total?Math.round(p.done/p.total*100):0}%</b></div><div className="insights-track"><span style={{width:(p.total?p.done/p.total*100:0)+'%'}}/></div></Link>)}{!active.length&&<p>No active projects.</p>}</section>
 <section className="insights-box"><h3>Project health</h3><p className="insights-note">Each project appears in one category.</p><div className="insights-health" aria-hidden="true">{[[onTrack,'#679fff'],[attention.length,'#ed9eb2'],[completed.length,'#80d6c4'],[archived.length,'#b49aee']].map(([n,c])=><span key={c} style={{width:(Number(n)/Math.max(1,data.projects.length)*100)+'%',background:String(c)}}/>)}</div><div className="insights-legend">{[['On track',onTrack],['Needs attention',attention.length],['Completed',completed.length],['Archived',archived.length]].map(([label,n])=><div key={label}><span>{label}</span><b>{n}</b></div>)}</div><p className="insights-note">Overdue or blocked active tasks flag a project for attention. An empty project can be on track without being complete.</p></section>
 <section className="insights-box insights-wide"><h3>{projectFilter==='all'?'All projects':projectFilter==='attention'?'Projects needing attention':projectFilter==='completed'?'Completed projects':projectFilter==='archived'?'Archived projects':'Active projects'} · {projects.length}</h3><div className="insights-project-list">{projects.slice(0,50).map(p=><Link href={'/dashboard/projects/'+p.id} key={p.id} className="insights-project-row"><div><strong>{p.name}</strong><small>Created by {p.creator} · {p.done}/{p.total} tasks completed</small></div><span>{p.is_archived?(p.completed_at?'Completed':'Archived'):p.attention?'Needs attention':'On track'}</span></Link>)}{!projects.length&&<p className="py-4">No matching projects.</p>}</div>{projects.length>50&&<p className="insights-note">Showing first 50. <Link href="/dashboard">Open Projects for the full list.</Link></p>}</section></div></section>
 <section aria-label="Task insights"><h3 className="insights-section-title">Task overview</h3><p className="insights-note">Unarchived tasks in active projects. Overdue is a subset of open tasks and excludes work awaiting review.</p><div className="insights-stats">{[['All tasks',total,''],['Open tasks',total-done,'pending'],['Overdue',data.overdue,'overdue'],['Completed',done,'done']].map(([label,n,filter])=><Link className="insights-stat" key={label} href={'/dashboard/tasks'+(filter?'?summary='+filter:'')}><span>{label}</span><strong>{n}</strong><small>View matching tasks →</small></Link>)}</div><div className="insights-grid"><section className="insights-box"><h3>Task status</h3><div className="insights-status"><div className="insights-donut" aria-hidden="true" style={{background:total?`conic-gradient(${gradient})`:'var(--glass-selected)'}}><div><strong>{total?Math.round(done/total*100):0}%</strong><small>completed</small></div></div><div className="insights-legend">{states.map(([id,label,color])=><div key={id}><span><i style={{background:color}}/>{label}</span><b>{data.status.find(s=>s.status===id)?.count||0}</b></div>)}</div></div>{!total&&<p className="insights-note">No active-project tasks yet.</p>}</section>
 <section className="insights-box"><h3>Completion trend</h3><p className="insights-note">{first.toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'Asia/Kolkata'})} · completion events by week (IST), including archived work.</p><div className="insights-bars">{data.trend.map(t=><div key={t.week}><b>{t.count}</b><span style={{height:(t.count/Math.max(...data.trend.map(x=>x.count))*100)+'px'}}/><small>{shortDate(t.week)}</small></div>)}</div>{!data.trend.length&&<p>No recorded completions this month.</p>}<p className="insights-note">Reapprovals count again; older imported dates may be estimated. <Link href={'/dashboard/reports?from='+month+'-01&to='+month+'-'+String(days).padStart(2,'0')}>Open report →</Link></p></section>
 <section className="insights-box"><h3>{data.isAdmin?'Team workload':'My workload'}</h3><p className="insights-note">Open active-project tasks. Shared tasks count for each assignee; these are counts, not effort estimates.</p>{data.workload.slice(0,20).map(p=><Link key={p.id||'unassigned'} className="insights-progress" href={'/dashboard/tasks?summary=pending&assignee='+(p.id||'unassigned')}><div><span>{p.name}</span><b>{p.count}</b></div><div className="insights-track"><span style={{width:(p.count/Math.max(...data.workload.map(x=>x.count))*100)+'%'}}/></div></Link>)}{!data.workload.length&&<p>No pending assignments.</p>}{data.workload.length>20&&<Link href="/dashboard/workload">View full workload →</Link>}</section>
 <section className="insights-box"><div className="insights-calendar-heading"><h3>{first.toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'Asia/Kolkata'})}</h3><div><button type="button" aria-label="Previous month" onClick={()=>moveMonth(-1)}><ChevronLeft className="h-4 w-4"/></button><button type="button" aria-label="Next month" onClick={()=>moveMonth(1)}><ChevronRight className="h-4 w-4"/></button></div></div><p className="insights-note">Select a date for open-task deadlines.</p><div className="insights-calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><span key={x}>{x}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0'),count=data.calendar.find(x=>x.day===key)?.count||0;return <button type="button" key={key} aria-label={`${key}, ${count} tasks due`} aria-pressed={day===key} onClick={()=>setDay(key)}>{i+1}{count>0&&<i/>}</button>;})}</div><div className="insights-agenda" aria-busy={agendaLoading}><strong>{shortDate(day)} · {agendaLoading?'…':data.deadlineTotal} tasks due</strong>{agendaLoading?<p role="status">Loading deadlines…</p>:<>{data.deadlines.map(t=><Link key={t.id} href={'/dashboard/projects/'+t.project_id+'?task='+t.id}><span>{t.title}</span><small>{t.project} · {states.find(s=>s[0]===t.status)?.[1]||t.status}</small></Link>)}{!data.deadlineTotal&&<p>No open-task deadlines on this date.</p>}{data.deadlineTotal>50&&<p>Showing the first 50 tasks.</p>}</>}</div></section></div></section>
 <p className="insights-note">Live counts are loaded when you open or refresh this dashboard. Project and task scopes differ as described above.</p>
 </>}
 </div>;
}
