'use client';
import {useState} from 'react';
import Link from 'next/link';
import {saveTaskView,deleteTaskView} from '@/app/dashboard/preferences/actions';
import {cleanView,type SavedTaskView} from '@/lib/task-views';
export default function SavedTaskViews({views,filters,onChange}:{views:SavedTaskView[];filters:Record<string,unknown>;onChange:(views:SavedTaskView[])=>void}){
 const [name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <details className="rounded-xl border bg-surface p-3"><summary className="cursor-pointer text-sm font-medium">Saved views {views.length?`(${views.length})`:''}</summary><div className="mt-3 space-y-3">{views.length>0&&<ul className="space-y-2">{views.map(view=><li key={view.id} className="flex items-center justify-between gap-3 text-sm"><Link className="min-w-0 break-words font-medium text-blue-600 underline" href={'/dashboard/tasks?'+new URLSearchParams(cleanView(view.filters))}>{view.name}</Link><button disabled={busy} aria-label={'Delete view '+view.name} className="shrink-0 rounded-lg border px-3 py-2" onClick={async()=>{setBusy(true);setError('');try{onChange(await deleteTaskView(view.id));}catch{setError('View could not be removed.');}finally{setBusy(false);}}}>Remove</button></li>)}</ul>}<form className="flex flex-wrap gap-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await saveTaskView(name,Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)])));if(result.error)setError(result.error);else if(result.views){onChange(result.views);setName('');}}catch{setError('View could not be saved.');}finally{setBusy(false);}}}><input aria-label="Saved view name" value={name} onChange={e=>setName(e.target.value)} required maxLength={60} placeholder="Name this view" className="min-w-0 flex-1 rounded-lg border p-2.5 text-sm"/><button disabled={busy||!name.trim()} className="rounded-lg border px-3 py-2 text-sm">{busy?'Saving…':'Save current view'}</button></form><p className="text-xs text-gray-500">Your filters are private to you and available on your other devices.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div></details>;
}
