'use client';
import {useEffect,useState,type ReactNode} from 'react';
type Receipt={id:string;user_id:string;accepted_at:string|null;acceptance_source?:string;name:string};
export default function TaskAcknowledgement({taskId,userId,readOnly=false,children}:{taskId:string;userId:string;readOnly?:boolean;children?:ReactNode}){
 const [receipts,setReceipts]=useState<Receipt[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/task-acknowledgement?task='+taskId,{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error);setReceipts(data.receipts);setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[taskId]);
 const own=receipts.find(r=>r.user_id===userId);
 const bottom=loaded&&(own?!!own.accepted_at:receipts.length>0&&receipts.every(r=>!!r.accepted_at));
 const box=loaded&&!receipts.length?null:<section className="my-4 rounded-xl border p-4" aria-label="Task acknowledgement"><h3 className="font-semibold">Assignee acknowledgements</h3><p className="my-2 text-sm text-gray-500">{loaded?`${receipts.filter(r=>r.accepted_at).length} of ${receipts.length} accepted`:'Loading acknowledgements…'}</p>{receipts.map(r=><div key={r.id} className="flex flex-wrap justify-between gap-2 border-t py-2 text-sm"><span>{r.name}{r.user_id===userId?' (you)':''}</span><span>{r.accepted_at?`${r.acceptance_source==='administrative'?'Accepted by admin':'Accepted'} · ${new Date(r.accepted_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST`:'Awaiting acceptance'}</span></div>)}{own&&!own.accepted_at&&!readOnly&&<><p className="my-3 text-sm text-gray-500">Confirm receipt of this task. Task status and approval rules stay unchanged; the creator will be notified.</p><button type="button" className="rounded-lg border px-4 py-2 text-sm" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/task-acknowledgement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:own.id})});const data=await r.json();if(!r.ok)throw Error(data.error);const updated=await fetch('/api/task-acknowledgement?task='+taskId,{cache:'no-store'});const result=await updated.json();if(!updated.ok)throw Error(result.error);setReceipts(result.receipts);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Confirming…':'Accept task'}</button></>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>;
 return <>{!bottom&&box}<div key="task-content">{children}</div>{bottom&&box}</>;
}
