'use client';
import {useState} from 'react';
import {reviewTask} from '@/app/dashboard/tasks/review';
import {assignedIds,type Task} from '@/lib/task-types';
export default function TaskReview({task,userId,isAdmin,readOnly,reviewEnabled,onBusyChange}:{task:Task;userId:string;isAdmin:boolean;readOnly:boolean;reviewEnabled:boolean;onBusyChange?:(busy:boolean)=>void}){
 const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const ids=assignedIds(task),reviewer=(isAdmin||(reviewEnabled&&task.created_by===userId))&&!ids.includes(userId),submitter=isAdmin||ids.includes(userId);
 const active=task.assignees?task.assignees.every(m=>m.is_active!==false):task.assignee?.is_active!==false;
 const submit=!readOnly&&submitter&&ids.length>0&&active&&!['done','in_review'].includes(task.status),decide=!readOnly&&reviewer&&task.status==='in_review',withdraw=!readOnly&&submitter&&task.status==='in_review',reopen=!readOnly&&task.status==='done'&&(isAdmin||task.created_by===userId);
 async function run(action:string){setBusy(true);onBusyChange?.(true);setError('');try{const r=await reviewTask(task.id,task.project_id,Number(task.review_version||0),action,reason);if(r.error)setError(r.error);else setReason('');}catch{setError('Could not confirm the review. Refresh and try again.');}finally{setBusy(false);onBusyChange?.(false);}}
 if(!active&&submitter&&!readOnly&&!['done','in_review'].includes(task.status))return <p className="my-4 text-sm text-gray-500">Reassign inactive teammates before submitting this shared task for review.</p>;
 if(!submit&&!decide&&!withdraw&&!reopen)return task.status==='in_review'?<p className="my-4 text-sm text-gray-500">Awaiting review by the task creator or an admin who is not assigned to this task.</p>:null;
 return <section className="my-4 space-y-3 rounded-xl border bg-surface p-4" aria-label="Task review"><h3 className="font-semibold">{reopen?'Completed task':'Review'}</h3><details className="text-sm text-gray-500"><summary className="cursor-pointer">Approval rules</summary><p className="mt-2">All assignees share one status. An eligible creator or admin outside the assignee group approves completion.</p></details>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{(decide||withdraw||reopen)&&<form onSubmit={e=>e.preventDefault()}><label className="block text-sm">Review feedback / reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} className="mt-1 w-full rounded-lg border p-3" placeholder="Required for changes, withdrawal or reopening."/></label></form>}<div className="flex flex-wrap gap-2">{submit&&<button disabled={busy} onClick={()=>run('submit')} className="rounded-lg border px-3 py-2 text-sm">Ready for review</button>}{decide&&<><button disabled={busy} onClick={()=>run('approve')} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">Approve & complete</button><button disabled={busy||!reason.trim()} onClick={()=>run('changes')} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50">Request changes</button></>}{withdraw&&<button disabled={busy||!reason.trim()} onClick={()=>run('withdraw')} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50">Withdraw submission</button>}{reopen&&<button disabled={busy||!reason.trim()} onClick={()=>run('reopen')} className="rounded-lg border px-3 py-2 text-sm disabled:opacity-50">Reopen task</button>}</div></section>;
}
