'use client';
import AssigneePicker from './AssigneePicker';
import {useEffect,useState} from 'react';
import {getSchedule,saveSchedule,type Schedule} from '@/app/dashboard/schedules/actions';
import {scheduleDates} from '@/lib/schedule-dates';
import {todayKey} from '@/lib/task-presentation';
import type {Member} from '@/lib/task-types';
function ScheduleForm({schedule,members,onSaved,onBusyChange}:{schedule:Schedule;members:Member[];onSaved:()=>Promise<void>;onBusyChange:(busy:boolean)=>void}){
 const tomorrow=new Date(Date.parse(todayKey())+86400000).toISOString().slice(0,10);
 const [frequency,setFrequency]=useState(schedule.frequency),[next,setNext]=useState(schedule.next_run<tomorrow?tomorrow:schedule.next_run),[end,setEnd]=useState(schedule.end_date||''),[paused,setPaused]=useState(schedule.paused),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 const readonly=!schedule.can_edit||schedule.archived;const field='mt-1 block w-full rounded-lg border p-2 text-sm';
 return <form className="space-y-3" onChange={()=>setPreview(false)} onSubmit={async e=>{e.preventDefault();if(!preview){setPreview(true);return;}setBusy(true);onBusyChange(true);setError('');try{const result=await saveSchedule(schedule.task_id,Number(schedule.version),new FormData(e.currentTarget));if(result.error)setError(result.error);else await onSaved();}catch{setError('Schedule change could not be confirmed. Reload before retrying.');}finally{setBusy(false);onBusyChange(false);}}}><p className="text-sm text-gray-500">These fields apply to future occurrences only. Existing task details and approvals stay unchanged.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<fieldset disabled={readonly||busy} className="grid gap-3 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Future task title<input name="title" defaultValue={schedule.title} required maxLength={200} className={field}/></label><label className="text-sm sm:col-span-2">Future description<textarea name="description" defaultValue={schedule.description||''} maxLength={10000} className={field}/></label><AssigneePicker members={members} initial={schedule.assignee_ids}/><label className="text-sm">Future priority<select name="priority" defaultValue={schedule.priority} className={field}>{['low','medium','high','urgent'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Frequency<select name="frequency" value={frequency} onChange={e=>setFrequency(e.target.value)} className={field}>{['daily','weekly','monthly'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Next future run<input name="next" type="date" min={paused?undefined:tomorrow} value={next} onChange={e=>setNext(e.target.value)} required className={field}/></label><label className="text-sm">End date (inclusive)<input name="end" type="date" min={paused?undefined:next} value={end} onChange={e=>setEnd(e.target.value)} className={field}/></label><label className="flex items-center gap-2 text-sm"><input name="paused" type="checkbox" checked={paused} onChange={e=>setPaused(e.target.checked)}/>Pause schedule</label></fieldset>{preview&&<div className="rounded-lg border p-3 text-sm"><strong>{paused?'Schedule will stay paused':'Next planned dates'}</strong>{!paused&&<ul className="mt-2 list-disc pl-5">{scheduleDates(next,frequency,(frequency!==schedule.frequency||next!==schedule.next_run)?next:schedule.anchor_date,end||null).map(x=><li key={x}>{x}</li>)}</ul>}<p className="mt-2 text-gray-500">Missed dates will not be recreated. An inactive creator or assignee holds generation until their access is restored.</p></div>}{!readonly&&<button disabled={busy} className="rounded-lg border px-4 py-2 text-sm">{preview?'Confirm future schedule':'Preview future schedule'}</button>}</form>;
}
export default function TaskSchedule({taskId,members,onBusyChange,active=true}:{taskId:string;members:Member[];onBusyChange:(busy:boolean)=>void;active?:boolean}){
 const [data,setData]=useState<Awaited<ReturnType<typeof getSchedule>>|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!active||data)return;let live=true;getSchedule(taskId).then(r=>{if(live)setData(r);}).catch(()=>{if(live)setError('Schedule could not load.');});return()=>{live=false};},[taskId,active,data]);
 async function reload(){setData(await getSchedule(taskId));}
 if(error)return <p role="alert">{error}</p>;if(!data?.schedule)return null;
 const s=data.schedule;return <section className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Recurring schedule</h3><p className="text-sm">{s.archived?'Held — archived work':s.held?'Held — inactive creator or assignee':s.paused?'Paused':s.end_date&&s.next_run>s.end_date?'Ended':'Running'} · Next scheduled date: {s.next_run}</p><details><summary className="cursor-pointer py-2 text-sm font-semibold">Edit future occurrences</summary><ScheduleForm key={String(s.version)} schedule={s} members={members} onSaved={reload} onBusyChange={onBusyChange}/></details>{data.events.length>0&&<details><summary className="cursor-pointer text-sm">Schedule history</summary>{data.events.map(e=><p key={e.id} className="mt-2 text-xs text-gray-500">{e.description} · {new Date(e.created_at).toLocaleString()}</p>)}</details>}</section>;
}
