'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {RefreshCw} from 'lucide-react';
import {historyAction,groupHistory,type HistoryEntry as Entry} from '@/lib/history-presentation';
export default function WorkspaceHistory({items,people}:{items:Entry[];people:{id:string;name:string}[]}){
 const [q,setQ]=useState(''),[kind,setKind]=useState(''),[person,setPerson]=useState('');const [pending,start]=useTransition();const router=useRouter();
 const names=new Map(people.map(p=>[p.id,p.name]));
 function value(v:unknown):string{if(v===null||v===undefined||v==='')return 'None';if(Array.isArray(v))return v.map(value).join(', ')||'None';if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return names.get(String(v))||String(v).replace(/\b[0-9a-f]{8}-[0-9a-f-]{27,}\b/g,id=>names.get(id)||'Unavailable item');}
 const groups=groupHistory(items);
 const filtered=groups.filter(records=>(!kind||records.some(e=>e.entity===kind))&&(!person||records.some(e=>e.actor_name===person))&&records.flatMap(e=>[e.actor_name,historyAction(e,names),e.title,e.project_name,e.action,...Object.entries(e.changes).flatMap(([field,v])=>[field,value(v.before),value(v.after)])]).join(' ').toLowerCase().includes(q.toLowerCase()));
 return <><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-surface p-4 text-xs text-gray-500"><span>Latest {items.length} audit records · {groups.length} activity entries · India time (IST)</span><button disabled={pending} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm" onClick={()=>start(()=>router.refresh())}><RefreshCw className="h-4 w-4"/>{pending?'Refreshing…':'Refresh'}</button></div><p className="text-xs text-gray-500">All filters search only the latest 20 audit records you can access, not the full history.</p><div className="flex flex-wrap gap-3"><input aria-label="Search the latest 20 history entries" placeholder="Search the latest 20 entries…" className="min-w-0 basis-full rounded-lg border bg-surface p-3 text-sm sm:basis-auto sm:flex-1" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Change type" className="rounded-lg border bg-surface p-3 text-sm" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All changes</option>{['Tasks','Projects','Remarks','Reviews','Attachments'].map(k=><option key={k}>{k}</option>)}</select><select aria-label="Changed by" className="max-w-full rounded-lg border bg-surface p-3 text-sm" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Everyone</option>{Array.from(new Set(items.map(e=>e.actor_name))).sort().map(n=><option key={n}>{n}</option>)}</select><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>{setQ('');setKind('');setPerson('');}}>Reset</button></div><section aria-label="Recent workspace history" className="divide-y rounded-2xl border bg-surface" aria-busy={pending}>{filtered.map(records=>{ const e=records[0];
 const href=e.task_exists?`/dashboard/projects/${e.project_id}?task=${e.task_id}${e.entity==='Remarks'&&e.action!=='deleted'?`&discussion=true#remark-${e.entity_id}`:''}`:e.project_exists?`/dashboard/projects/${e.project_id}`:null;
 return <article key={e.id} className="flex items-start gap-3 p-4 sm:p-5"><span aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-xs font-semibold text-blue-600">{e.actor_name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm"><strong>{e.actor_name}</strong> {historyAction(e,names)}</p><time dateTime={e.created_at} className="text-xs tabular-nums text-gray-500">{new Date(e.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'})} IST</time></div>{href?<Link className="mt-1 inline-block max-w-full [overflow-wrap:anywhere] font-semibold text-blue-600" href={href}>{e.title} ↗</Link>:<p className="mt-1 break-words font-semibold">{e.title} · Deleted</p>}<p className="mt-1 text-xs text-gray-500">{e.project_name}</p><details className="mt-2 text-sm"><summary className="cursor-pointer text-gray-500">View audit details{records.length>1?` (${records.length} linked records)`:''}</summary><div className="mt-3 space-y-3">{records.map(record=><div key={record.id} className="rounded-lg border p-3"><p className="text-xs text-gray-500 break-all">{record.entity} · {record.action} · Record {record.id}</p><time className="text-xs tabular-nums text-gray-500" dateTime={record.created_at}>{new Date(record.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</time><dl className="mt-3 space-y-3">{Object.entries(record.changes).map(([field,v])=><div key={field}><dt className="text-xs font-semibold text-gray-500">{field}</dt><dd className="mt-1 whitespace-pre-wrap [overflow-wrap:anywhere] text-sm">{value(v.before)} <span className="text-gray-500">→</span> {value(v.after)}</dd></div>)}</dl><details className="mt-2"><summary className="cursor-pointer text-xs text-gray-500">Raw record</summary><pre className="mt-2 whitespace-pre-wrap [overflow-wrap:anywhere] text-xs">{JSON.stringify(record,null,2)}</pre></details></div>)}</div></details></div></article>;
 })}{!filtered.length&&<p className="p-6 text-sm text-gray-500">{items.length?'No recent changes match these filters.':'No recorded activity yet.'}</p>}</section><p className="text-xs text-gray-500">Showing {filtered.length} of {groups.length} activity entries from the latest {items.length} audit records (maximum 20). Linked changes share an entry; every original record remains in its details. Older records remain stored. Historical changes without a verified link stay separate.</p></>;
}
